$(document).ready(
  function() {
    buildTable()
    $('#example').DataTable();
  }
);

  function buildTable() {
    for (town of townInformation) {
        let table = document.getElementById("tableBody")
        buildSection(table, town);
    }
  }

  function buildSection(table, town) {
    for (i = 0; i < town.troops.length; i++) {
        let row = buildRow(town.name,  i+1, town.troops[i])
	table.append(row)
    } 
  }

  function buildRow(name, index, troop) {
    let prepend = "/lv"
    let append = ""
    if (troop.upgraded) {
	append = "upg"
    }
    let imageSrc = "./img/" + name + "/" + troop.name + ".PNG"

    let row = document.createElement("tr")
    let cell = document.createElement("td")
    cell.innerHTML = name;
    row.append(cell)
    
    cell = document.createElement("td")
    cell.innerHTML = troop.name;
    row.append(cell)

    cell = document.createElement("td")
    cell.innerHTML = "Level " + troop.level + " " + append;
    row.append(cell)

    cell = document.createElement("td")
    cell.innerHTML = '<img src="' + imageSrc + '">';
    row.append(cell)

    cell = document.createElement("td")
    cell.innerHTML = troop.type;
    row.append(cell)

    cell = document.createElement("td")
    cell.innerHTML = troop.damage[0] + "-" + troop.damage[troop.damage.length-1];
    row.append(cell)

    cell = document.createElement("td")
    cell.innerHTML = troop.health;
    row.append(cell)

    cell = document.createElement("td")
    cell.innerHTML = troop.speed;
    row.append(cell)
    
    return row
  }
    
  let townInformation = 
      [
	{
	  "name": "Castle",
	  "troops":
	    [
	      {
		"level": 1,
		"upgraded": false,
		"name": "Pikemen",
		"type": "Weak ass lookin head ass",
		"attack": 4,
		"defense": 5,
		"damage": [1, 2, 3],
                "archerDamage": 0,
		"health": 10,
		"speed": "Extra Slow",
		"distancePerMove": 4,
		"cost": 60,
		"createdPerWeek": 14,
		"movementType": "Ground",
	      },
	      {
		"level": 1,
		"upgraded": true,
		"name": "Halberdiers",
		"type": "Weak ass lookin head ass",
		"archerDamage": 0,
		"attack": 6,
		"defense": 5,
		"damage": [2, 3],
		"health": 10,
		"speed": "Slow",
		"distancePerMove": 5,
		"cost": 75,
		"createdPerWeek": 14,
		"movementType": "Ground",
	      },
	      {
		"level": 2,
		"upgraded": false,
		"name": "Archers",
		"type": "Archer",
                "archerDamage": 12,
		"attack": 6,
		"defense": 3,
		"damage": [2, 3],
		"health": 10,
		"speed": "Extra Slow",
		"distancePerMove":4,
		"cost": 100,
		"createdPerWeek": 9,
		"movementType": "Ground",
	      },
	      {
		"level": 2,
		"upgraded": true,
		"name": "Marksmen",
		"type": "Archer",
                "archerDamage": 24,
		"attack": 6,
		"defense": 3,
		"damage": [2, 3],
		"health": 10,
		"speed": "Slow",
		"distancePerMove":6,
		"cost": 150,
		"createdPerWeek": 9,
		"movementType": "Ground",
	      },
	      {
		"level": 3,
		"upgraded": false,
		"name": "Griffins",
		"type": "Fast as Fuck boi",
                "archerDamage": 0,
		"attack": 6,
		"defense": 5,
		"damage": [1, 2, 3],
		"health": 10,
		"speed": "Very Swift",
		"distancePerMove": 6,
		"cost": 200,
		"createdPerWeek": 14,
		"movementType": "Flying",
	      },
	      {
		"level": 3,
		"upgraded": true,
		"name": "Royal Griffins",
		"type": "Fast as Fuck boi",
                "archerDamage": 0,
		"attack": 6,
		"defense": 5,
		"damage": [1, 2, 3],
		"health": 10,
		"speed": "Ultra Swift",
		"distancePerMove": 9,
		"cost": 240,
		"createdPerWeek": 7,
		"movementType": "Flying",
	      },
	      {
		"level": 4,
		"upgraded": false,
		"name": "Swordsmen",
		"type": "Weak ass lookin head ass",
                "archerDamage": 0,
		"attack": 6,
		"defense": 5,
		"damage": [6, 7, 8, 9],
		"health": 35,
		"speed": "Slow",
		"distancePerMove": 5,
		"cost": 300,
		"createdPerWeek": 4,
		"movementType": "Ground",
	      },
	      {
		"level": 4,
		"upgraded": true,
		"name": "Crusaders",
		"type": "Weak ass lookin head ass",
                "archerDamage": 0,
		"attack": 12,
		"defense": 12,
		"damage": [7, 8, 9, 10],
		"health": 35,
		"speed": "Swift",
		"distancePerMove": 4,
		"cost": 400,
		"createdPerWeek": 4,
		"movementType": "Ground",
	      },
	      {
		"level": 5,
		"upgraded": false,
		"name": "Monks",
		"type": "Archer",
                "archerDamage": 12,
		"attack": 12,
		"defense": 7,
		"damage": [10, 11, 12],
		"health": 30,
		"speed": "Slow",
		"distancePerMove": 5,
		"cost": 400,
		"createdPerWeek": 3,
		"movementType": "Ground",
	      },
	      {
		"level": 5,
		"upgraded": true,
		"name": "Zealots",
		"type": "Archer",
                "archerDamage": 0,
		"attack": 6,
		"defense": 5,
		"damage": [10, 12],
		"health": 30,
		"speed": "Extra Swift",
		"distancePerMove": 7,
		"cost": 450,
		"createdPerWeek": 3,
		"movementType": "Ground",
	      },
	      {
		"level": 6,
		"upgraded": false,
		"name": "Cavaliers",
		"type": "Fast as fuck boi",
                "archerDamage": 0,
		"attack": 15,
		"defense": 15,
		"damage": [15, 25],
		"health": 100,
		"speed": 4,
		"cost": 60,
		"createdPerWeek": 14,
		"movementType": "Ground",
	      },
	      {
		"level": 6,
		"upgraded": true,
		"name": "Champions",
		"type": "Weak ass lookin head ass",
                "archerDamage": 0,
		"attack": 6,
		"defense": 5,
		"damage": [1, 2, 3],
		"health": 10,
		"speed": 4,
		"cost": 60,
		"createdPerWeek": 14,
		"movementType": "Ground",
	      },
	      {
		"level": 7,
		"upgraded": false,
		"name": "Angels",
		"type": "Weak ass lookin head ass",
                "archerDamage": 0,
		"attack": 6,
		"defense": 5,
		"damage": [1, 2, 3],
		"health": 10,
		"speed": 4,
		"cost": 60,
		"createdPerWeek": 14,
		"movementType": "Ground",
	      },
	      {
		"level": 7,
		"upgraded": true,
		"name": "Archangels",
		"type": "Weak ass lookin head ass",
                "archerDamage": 0,
		"attack": 6,
		"defense": 5,
		"damage": [1, 2, 3],
		"health": 10,
		"speed": 4,
		"cost": 60,
		"createdPerWeek": 14,
		"movementType": "Ground",
	      }
	    ]
	},
	{
	  "name": "Conflux",
	  "troops":
	    [
	      {
		"level": 1,
		"upgraded": false,
		"name": "Pixies",
		"type": "Weak ass lookin head ass",
		"damage": 2,
		"health": 10,
		"speed": 7,
	      },
	      {
		"level": 1,
		"upgraded": true,
		"name": "Sprites",
		"type": "Weak ass lookin head ass",
		"damage": 2,
		"health": 10,
		"speed": 7,
	      },
	      {
		"level": 2,
		"upgraded": false,
		"name": "Air Elementals",
		"type": "Weak ass lookin head ass",
		"damage": 2,
		"health": 10,
		"speed": 7,
	      },
	      {
		"level": 2,
		"upgraded": true,
		"name": "Storm Elementals",
		"type": "Weak ass lookin head ass",
		"damage": 2,
		"health": 10,
		"speed": 7,
	      },
	      {
		"level": 3,
		"upgraded": false,
		"name": "Water Elementals",
		"type": "Weak ass lookin head ass",
		"damage": 2,
		"health": 10,
		"speed": 7,
	      },
	      {
		"level": 3,
		"upgraded": true,
		"name": "Ice Elementals",
		"type": "Weak ass lookin head ass",
		"damage": 2,
		"health": 10,
		"speed": 7,
	      },
	      {
		"level": 4,
		"upgraded": false,
		"name": "Fire Elementals",
		"type": "Weak ass lookin head ass",
		"damage": 2,
		"health": 10,
		"speed": 7,
	      },
	      {
		"level": 4,
		"upgraded": true,
		"name": "Energy Elementals",
		"type": "Weak ass lookin head ass",
		"damage": 2,
		"health": 10,
		"speed": 7,
	      },
	      {
		"level": 5,
		"upgraded": false,
		"name": "Earth Elementals",
		"type": "Weak ass lookin head ass",
		"damage": 2,
		"health": 10,
		"speed": 7,
	      },
	      {
		"level": 5,
		"upgraded": true,
		"name": "Magma Elementals",
		"type": "Weak ass lookin head ass",
		"damage": 2,
		"health": 10,
		"speed": 7,
	      },
	      {
		"level": 6,
		"upgraded": false,
		"name": "Psychic Elementals",
		"type": "Weak ass lookin head ass",
		"damage": 2,
		"health": 10,
		"speed": 7,
	      },
	      {
		"level": 6,
		"upgraded": true,
		"name": "Magic Elementals",
		"type": "Weak ass lookin head ass",
		"damage": 2,
		"health": 10,
		"speed": 7,
	      },
	      {
		"level": 7,
		"upgraded": false,
		"name": "Firebirds",
		"type": "Weak ass lookin head ass",
		"damage": 2,
		"health": 10,
		"speed": 7,
	      },
	      {
		"level": 7,
		"upgraded": true,
		"name": "Phoenixes",
		"type": "Weak ass lookin head ass",
		"damage": 2,
		"health": 10,
		"speed": 7,
	      }
	    ]
	  },
	{
	  "name": "Cove",
	  "troops":
	    [
	      {
		"level": 1,
		"upgraded": false,
		"name": "Nymphs",
		"type": "Weak ass lookin head ass",
		"damage": 2,
		"health": 10,
		"speed": 7,
	      },
	      {
		"level": 1,
		"upgraded": true,
		"name": "Oceanids",
		"type": "Weak ass lookin head ass",
		"damage": 2,
		"health": 10,
		"speed": 7,
	      },
	      {
		"level": 2,
		"upgraded": false,
		"name": "Crew Mates",
		"type": "Weak ass lookin head ass",
		"damage": 2,
		"health": 10,
		"speed": 7,
	      },
	      {
		"level": 2,
		"upgraded": true,
		"name": "Seamen",
		"type": "Weak ass lookin head ass",
		"damage": 2,
		"health": 10,
		"speed": 7,
	      },
	      {
		"level": 3,
		"upgraded": false,
		"name": "Pirates",
		"type": "Weak ass lookin head ass",
		"damage": 2,
		"health": 10,
		"speed": 7,
	      },
	      {
		"level": 3,
		"upgraded": true,
		"name": "Corsairs",
		"type": "Weak ass lookin head ass",
		"damage": 2,
		"health": 10,
		"speed": 7,
	      },
	      {
		"level": 3,
		"upgraded": true,
		"name": "Sea Dogs",
		"type": "Weak ass lookin head ass",
		"damage": 2,
		"health": 10,
		"speed": 7,
	      },
	      {
		"level": 4,
		"upgraded": false,
		"name": "Stormbirds",
		"type": "Weak ass lookin head ass",
		"damage": 2,
		"health": 10,
		"speed": 7,
	      },
	      {
		"level": 4,
		"upgraded": true,
		"name": "Ayssids",
		"type": "Weak ass lookin head ass",
		"damage": 2,
		"health": 10,
		"speed": 7,
	      },
	      {
		"level": 5,
		"upgraded": false,
		"name": "Sea Witches",
		"type": "Weak ass lookin head ass",
		"damage": 2,
		"health": 10,
		"speed": 7,
	      },
	      {
		"level": 5,
		"upgraded": true,
		"name": "Sorceresses",
		"type": "Weak ass lookin head ass",
		"damage": 2,
		"health": 10,
		"speed": 7,
	      },
	      {
		"level": 6,
		"upgraded": false,
		"name": "Nix",
		"type": "Weak ass lookin head ass",
		"damage": 2,
		"health": 10,
		"speed": 7,
	      },
	      {
		"level": 6,
		"upgraded": true,
		"name": "Nix Warriors",
		"type": "Weak ass lookin head ass",
		"damage": 2,
		"health": 10,
		"speed": 7,
	      },
	      {
		"level": 7,
		"upgraded": false,
		"name": "Sea Serpents",
		"type": "Weak ass lookin head ass",
		"damage": 2,
		"health": 10,
		"speed": 7,
	      },
	      {
		"level": 7,
		"upgraded": true,
		"name": "Haspids",
		"type": "Weak ass lookin head ass",
		"damage": 2,
		"health": 10,
		"speed": 7,
	      }
	    ]
	  },
	{
	  "name": "Dungeon",
	  "troops":
	    [
	      {
		"level": 1,
		"upgraded": false,
		"name": "Troglodytes",
		"type": "Weak ass lookin head ass",
		"damage": 2,
		"health": 10,
		"speed": 7,
	      },
	      {
		"level": 1,
		"upgraded": true,
		"name": "Infernal Troglodytes",
		"type": "Weak ass lookin head ass",
		"damage": 2,
		"health": 10,
		"speed": 7,
	      },
	      {
		"level": 2,
		"upgraded": false,
		"name": "Harpies",
		"type": "Weak ass lookin head ass",
		"damage": 2,
		"health": 10,
		"speed": 7,
	      },
	      {
		"level": 2,
		"upgraded": true,
		"name": "Harpy Hags",
		"type": "Weak ass lookin head ass",
		"damage": 2,
		"health": 10,
		"speed": 7,
	      },
	      {
		"level": 3,
		"upgraded": false,
		"name": "Beholders",
		"type": "Weak ass lookin head ass",
		"damage": 2,
		"health": 10,
		"speed": 7,
	      },
	      {
		"level": 3,
		"upgraded": true,
		"name": "Evil Eyes",
		"type": "Weak ass lookin head ass",
		"damage": 2,
		"health": 10,
		"speed": 7,
	      },
	      {
		"level": 4,
		"upgraded": false,
		"name": "Medusas",
		"type": "Weak ass lookin head ass",
		"damage": 2,
		"health": 10,
		"speed": 7,
	      },
	      {
		"level": 4,
		"upgraded": true,
		"name": "Medusa Queens",
		"type": "Weak ass lookin head ass",
		"damage": 2,
		"health": 10,
		"speed": 7,
	      },
	      {
		"level": 5,
		"upgraded": false,
		"name": "Minotaurs",
		"type": "Weak ass lookin head ass",
		"damage": 2,
		"health": 10,
		"speed": 7,
	      },
	      {
		"level": 5,
		"upgraded": true,
		"name": "Minotaur Kings",
		"type": "Weak ass lookin head ass",
		"damage": 2,
		"health": 10,
		"speed": 7,
	      },
	      {
		"level": 6,
		"upgraded": false,
		"name": "Manticores",
		"type": "Weak ass lookin head ass",
		"damage": 2,
		"health": 10,
		"speed": 7,
	      },
	      {
		"level": 6,
		"upgraded": true,
		"name": "Scorpicores",
		"type": "Weak ass lookin head ass",
		"damage": 2,
		"health": 10,
		"speed": 7,
	      },
	      {
		"level": 7,
		"upgraded": false,
		"name": "Red Dragons",
		"type": "Weak ass lookin head ass",
		"damage": 2,
		"health": 10,
		"speed": 7,
	      },
	      {
		"level": 7,
		"upgraded": true,
		"name": "Black Dragons",
		"type": "Weak ass lookin head ass",
		"damage": 2,
		"health": 10,
		"speed": 7,
	      }
	    ]
	  },
	{
	  "name": "Fortress",
	  "troops":
	    [
	      {
		"level": 1,
		"upgraded": false,
		"name": "Gnolls",
		"type": "Weak ass lookin head ass",
		"damage": 2,
		"health": 10,
		"speed": 7,
	      },
	      {
		"level": 1,
		"upgraded": true,
		"name": "Gnoll Marauders",
		"type": "Weak ass lookin head ass",
		"damage": 2,
		"health": 10,
		"speed": 7,
	      },
	      {
		"level": 2,
		"upgraded": false,
		"name": "Lizardmen",
		"type": "Weak ass lookin head ass",
		"damage": 2,
		"health": 10,
		"speed": 7,
	      },
	      {
		"level": 2,
		"upgraded": true,
		"name": "Lizard Warriors",
		"type": "Weak ass lookin head ass",
		"damage": 2,
		"health": 10,
		"speed": 7,
	      },
	      {
		"level": 3,
		"upgraded": false,
		"name": "Serpent Flies",
		"type": "Weak ass lookin head ass",
		"damage": 2,
		"health": 10,
		"speed": 7,
	      },
	      {
		"level": 3,
		"upgraded": true,
		"name": "Dragon Flies",
		"type": "Weak ass lookin head ass",
		"damage": 2,
		"health": 10,
		"speed": 7,
	      },
	      {
		"level": 4,
		"upgraded": false,
		"name": "Basililsk",
		"type": "Weak ass lookin head ass",
		"damage": 2,
		"health": 10,
		"speed": 7,
	      },
	      {
		"level": 4,
		"upgraded": true,
		"name": "Greater Basilisks",
		"type": "Weak ass lookin head ass",
		"damage": 2,
		"health": 10,
		"speed": 7,
	      },
	      {
		"level": 5,
		"upgraded": false,
		"name": "Gorgons",
		"type": "Weak ass lookin head ass",
		"damage": 2,
		"health": 10,
		"speed": 7,
	      },
	      {
		"level": 5,
		"upgraded": true,
		"name": "Mighty Gorgons",
		"type": "Weak ass lookin head ass",
		"damage": 2,
		"health": 10,
		"speed": 7,
	      },
	      {
		"level": 6,
		"upgraded": false,
		"name": "Wyverns",
		"type": "Weak ass lookin head ass",
		"damage": 2,
		"health": 10,
		"speed": 7,
	      },
	      {
		"level": 6,
		"upgraded": true,
		"name": "Wyvern Monarchs",
		"type": "Weak ass lookin head ass",
		"damage": 2,
		"health": 10,
		"speed": 7,
	      },
	      {
		"level": 7,
		"upgraded": false,
		"name": "Hydras",
		"type": "Weak ass lookin head ass",
		"damage": 2,
		"health": 10,
		"speed": 7,
	      },
	      {
		"level": 7,
		"upgraded": true,
		"name": "Chaos Hydras",
		"type": "Weak ass lookin head ass",
		"damage": 2,
		"health": 10,
		"speed": 7,
	      }
	    ]
	  },
	{
	  "name": "Inferno",
	  "troops":
	    [
	      {
		"level": 1,
		"upgraded": false,
		"name": "Imps",
		"type": "Weak ass lookin head ass",
		"damage": 2,
		"health": 10,
		"speed": 7,
	      },
	      {
		"level": 1,
		"upgraded": true,
		"name": "Familiars",
		"type": "Weak ass lookin head ass",
		"damage": 2,
		"health": 10,
		"speed": 7,
	      },
	      {
		"level": 2,
		"upgraded": false,
		"name": "Gogs",
		"type": "Weak ass lookin head ass",
		"damage": 2,
		"health": 10,
		"speed": 7,
	      },
	      {
		"level": 2,
		"upgraded": true,
		"name": "Magogs",
		"type": "Weak ass lookin head ass",
		"damage": 2,
		"health": 10,
		"speed": 7,
	      },
	      {
		"level": 3,
		"upgraded": false,
		"name": "Hell Hounds",
		"type": "Weak ass lookin head ass",
		"damage": 2,
		"health": 10,
		"speed": 7,
	      },
	      {
		"level": 3,
		"upgraded": true,
		"name": "Cerberi",
		"type": "Weak ass lookin head ass",
		"damage": 2,
		"health": 10,
		"speed": 7,
	      },
	      {
		"level": 4,
		"upgraded": false,
		"name": "Demons",
		"type": "Weak ass lookin head ass",
		"damage": 2,
		"health": 10,
		"speed": 7,
	      },
	      {
		"level": 4,
		"upgraded": true,
		"name": "Horned Demons",
		"type": "Weak ass lookin head ass",
		"damage": 2,
		"health": 10,
		"speed": 7,
	      },
	      {
		"level": 5,
		"upgraded": false,
		"name": "Pit Fiends",
		"type": "Weak ass lookin head ass",
		"damage": 2,
		"health": 10,
		"speed": 7,
	      },
	      {
		"level": 5,
		"upgraded": true,
		"name": "Pit Lords",
		"type": "Weak ass lookin head ass",
		"damage": 2,
		"health": 10,
		"speed": 7,
	      },
	      {
		"level": 6,
		"upgraded": false,
		"name": "Efreet",
		"type": "Weak ass lookin head ass",
		"damage": 2,
		"health": 10,
		"speed": 7,
	      },
	      {
		"level": 6,
		"upgraded": true,
		"name": "Efreet Sultans",
		"type": "Weak ass lookin head ass",
		"damage": 2,
		"health": 10,
		"speed": 7,
	      },
	      {
		"level": 7,
		"upgraded": false,
		"name": "Devils",
		"type": "Weak ass lookin head ass",
		"damage": 2,
		"health": 10,
		"speed": 7,
	      },
	      {
		"level": 7,
		"upgraded": true,
		"name": "Arch Devils",
		"type": "Weak ass lookin head ass",
		"damage": 2,
		"health": 10,
		"speed": 7,
	      }
	    ]
	  },
	{
	  "name": "Necropolis",
	  "troops":
	    [
	      {
		"level": 1,
		"upgraded": false,
		"name": "Skeletons",
		"type": "Weak ass lookin head ass",
		"damage": 2,
		"health": 10,
		"speed": 7,
	      },
	      {
		"level": 1,
		"upgraded": true,
		"name": "Skeleton Warriors",
		"type": "Weak ass lookin head ass",
		"damage": 2,
		"health": 10,
		"speed": 7,
	      },
	      {
		"level": 2,
		"upgraded": false,
		"name": "Walking Dead",
		"type": "Weak ass lookin head ass",
		"damage": 2,
		"health": 10,
		"speed": 7,
	      },
	      {
		"level": 2,
		"upgraded": true,
		"name": "Zombies",
		"type": "Weak ass lookin head ass",
		"damage": 2,
		"health": 10,
		"speed": 7,
	      },
	      {
		"level": 3,
		"upgraded": false,
		"name": "Wights",
		"type": "Weak ass lookin head ass",
		"damage": 2,
		"health": 10,
		"speed": 7,
	      },
	      {
		"level": 3,
		"upgraded": true,
		"name": "Wraiths",
		"type": "Weak ass lookin head ass",
		"damage": 2,
		"health": 10,
		"speed": 7,
	      },
	      {
		"level": 4,
		"upgraded": false,
		"name": "Vampires",
		"type": "Weak ass lookin head ass",
		"damage": 2,
		"health": 10,
		"speed": 7,
	      },
	      {
		"level": 4,
		"upgraded": true,
		"name": "Vampire Lords",
		"type": "Weak ass lookin head ass",
		"damage": 2,
		"health": 10,
		"speed": 7,
	      },
	      {
		"level": 5,
		"upgraded": false,
		"name": "Liches",
		"type": "Weak ass lookin head ass",
		"damage": 2,
		"health": 10,
		"speed": 7,
	      },
	      {
		"level": 5,
		"upgraded": true,
		"name": "Power Liches",
		"type": "Weak ass lookin head ass",
		"damage": 2,
		"health": 10,
		"speed": 7,
	      },
	      {
		"level": 6,
		"upgraded": false,
		"name": "Black Knights",
		"type": "Weak ass lookin head ass",
		"damage": 2,
		"health": 10,
		"speed": 7,
	      },
	      {
		"level": 6,
		"upgraded": true,
		"name": "Dread Knights",
		"type": "Weak ass lookin head ass",
		"damage": 2,
		"health": 10,
		"speed": 7,
	      },
	      {
		"level": 7,
		"upgraded": false,
		"name": "Bone Dragons",
		"type": "Weak ass lookin head ass",
		"damage": 2,
		"health": 10,
		"speed": 7,
	      },
	      {
		"level": 7,
		"upgraded": true,
		"name": "Ghost Dragons",
		"type": "Weak ass lookin head ass",
		"damage": 2,
		"health": 10,
		"speed": 7,
	      }
	    ]
	  },
	{
	  "name": "Rampart",
	  "troops":
	    [
	      {
		"level": 1,
		"upgraded": false,
		"name": "Centaurs",
		"type": "Weak ass lookin head ass",
		"damage": 2,
		"health": 10,
		"speed": 7,
	      },
	      {
		"level": 1,
		"upgraded": true,
		"name": "Centaur Captains",
		"type": "Weak ass lookin head ass",
		"damage": 2,
		"health": 10,
		"speed": 7,
	      },
	      {
		"level": 2,
		"upgraded": false,
		"name": "Dwarves",
		"type": "Weak ass lookin head ass",
		"damage": 2,
		"health": 10,
		"speed": 7,
	      },
	      {
		"level": 2,
		"upgraded": true,
		"name": "Battle Dwarves",
		"type": "Weak ass lookin head ass",
		"damage": 2,
		"health": 10,
		"speed": 7,
	      },
	      {
		"level": 3,
		"upgraded": false,
		"name": "Wood Elves",
		"type": "Weak ass lookin head ass",
		"damage": 2,
		"health": 10,
		"speed": 7,
	      },
	      {
		"level": 3,
		"upgraded": true,
		"name": "Grand Elves",
		"type": "Weak ass lookin head ass",
		"damage": 2,
		"health": 10,
		"speed": 7,
	      },
	      {
		"level": 4,
		"upgraded": false,
		"name": "Pegasi",
		"type": "Weak ass lookin head ass",
		"damage": 2,
		"health": 10,
		"speed": 7,
	      },
	      {
		"level": 4,
		"upgraded": true,
		"name": "Silver Pegasi",
		"type": "Weak ass lookin head ass",
		"damage": 2,
		"health": 10,
		"speed": 7,
	      },
	      {
		"level": 5,
		"upgraded": false,
		"name": "Dendroid Guards",
		"type": "Weak ass lookin head ass",
		"damage": 2,
		"health": 10,
		"speed": 7,
	      },
	      {
		"level": 5,
		"upgraded": true,
		"name": "Dendroid Soldiers",
		"type": "Weak ass lookin head ass",
		"damage": 2,
		"health": 10,
		"speed": 7,
	      },
	      {
		"level": 6,
		"upgraded": false,
		"name": "Unicorns",
		"type": "Weak ass lookin head ass",
		"damage": 2,
		"health": 10,
		"speed": 7,
	      },
	      {
		"level": 6,
		"upgraded": true,
		"name": "War Unicorns",
		"type": "Weak ass lookin head ass",
		"damage": 2,
		"health": 10,
		"speed": 7,
	      },
	      {
		"level": 7,
		"upgraded": false,
		"name": "Green Dragons",
		"type": "Weak ass lookin head ass",
		"damage": 2,
		"health": 10,
		"speed": 7,
	      },
	      {
		"level": 7,
		"upgraded": true,
		"name": "Gold Dragons",
		"type": "Weak ass lookin head ass",
		"damage": 2,
		"health": 10,
		"speed": 7,
	      }
	    ]
	  },
	{
	  "name": "Stronghold",
	  "troops":
	    [
	      {
		"level": 1,
		"upgraded": false,
		"name": "Goblins",
		"type": "Weak ass lookin head ass",
		"damage": 2,
		"health": 10,
		"speed": 7,
	      },
	      {
		"level": 1,
		"upgraded": true,
		"name": "Hobgoblins",
		"type": "Weak ass lookin head ass",
		"damage": 2,
		"health": 10,
		"speed": 7,
	      },
	      {
		"level": 2,
		"upgraded": false,
		"name": "Wolf Riders",
		"type": "Weak ass lookin head ass",
		"damage": 2,
		"health": 10,
		"speed": 7,
	      },
	      {
		"level": 2,
		"upgraded": true,
		"name": "Wolf Raiders",
		"type": "Weak ass lookin head ass",
		"damage": 2,
		"health": 10,
		"speed": 7,
	      },
	      {
		"level": 3,
		"upgraded": false,
		"name": "Orcs",
		"type": "Weak ass lookin head ass",
		"damage": 2,
		"health": 10,
		"speed": 7,
	      },
	      {
		"level": 3,
		"upgraded": true,
		"name": "Orc Chieftains",
		"type": "Weak ass lookin head ass",
		"damage": 2,
		"health": 10,
		"speed": 7,
	      },
	      {
		"level": 4,
		"upgraded": false,
		"name": "Ogres",
		"type": "Weak ass lookin head ass",
		"damage": 2,
		"health": 10,
		"speed": 7,
	      },
	      {
		"level": 4,
		"upgraded": true,
		"name": "Ogre Magi",
		"type": "Weak ass lookin head ass",
		"damage": 2,
		"health": 10,
		"speed": 7,
	      },
	      {
		"level": 5,
		"upgraded": false,
		"name": "Rocs",
		"type": "Weak ass lookin head ass",
		"damage": 2,
		"health": 10,
		"speed": 7,
	      },
	      {
		"level": 5,
		"upgraded": true,
		"name": "Thunder Birds",
		"type": "Weak ass lookin head ass",
		"damage": 2,
		"health": 10,
		"speed": 7,
	      },
	      {
		"level": 6,
		"upgraded": false,
		"name": "Cyclopes",
		"type": "Weak ass lookin head ass",
		"damage": 2,
		"health": 10,
		"speed": 7,
	      },
	      {
		"level": 6,
		"upgraded": true,
		"name": "Cyclops Kings",
		"type": "Weak ass lookin head ass",
		"damage": 2,
		"health": 10,
		"speed": 7,
	      },
	      {
		"level": 7,
		"upgraded": false,
		"name": "Behemoths",
		"type": "Weak ass lookin head ass",
		"damage": 2,
		"health": 10,
		"speed": 7,
	      },
	      {
		"level": 7,
		"upgraded": true,
		"name": "Ancient Behemoths",
		"type": "Weak ass lookin head ass",
		"damage": 2,
		"health": 10,
		"speed": 7,
	      }
	    ]
	  },
	{
	  "name": "Tower",
	  "troops":
	    [
	      {
		"level": 1,
		"upgraded": false,
		"name": "Gremlins",
		"type": "Weak ass lookin head ass",
		"damage": 2,
		"health": 10,
		"speed": 7,
	      },
	      {
		"level": 1,
		"upgraded": true,
		"name": "Master Gremlins",
		"type": "Weak ass lookin head ass",
		"damage": 2,
		"health": 10,
		"speed": 7,
	      },
	      {
		"level": 2,
		"upgraded": false,
		"name": "Stone Gargoyles",
		"type": "Weak ass lookin head ass",
		"damage": 2,
		"health": 10,
		"speed": 7,
	      },
	      {
		"level": 2,
		"upgraded": true,
		"name": "Obsidian Gargoyles",
		"type": "Weak ass lookin head ass",
		"damage": 2,
		"health": 10,
		"speed": 7,
	      },
	      {
		"level": 3,
		"upgraded": false,
		"name": "Stone Golems",
		"type": "Weak ass lookin head ass",
		"damage": 2,
		"health": 10,
		"speed": 7,
	      },
	      {
		"level": 3,
		"upgraded": true,
		"name": "Iron Golems",
		"type": "Weak ass lookin head ass",
		"damage": 2,
		"health": 10,
		"speed": 7,
	      },
	      {
		"level": 4,
		"upgraded": false,
		"name": "Magi",
		"type": "Weak ass lookin head ass",
		"damage": 2,
		"health": 10,
		"speed": 7,
	      },
	      {
		"level": 4,
		"upgraded": true,
		"name": "Arch Magi",
		"type": "Weak ass lookin head ass",
		"damage": 2,
		"health": 10,
		"speed": 7,
	      },
	      {
		"level": 5,
		"upgraded": false,
		"name": "Genies",
		"type": "Weak ass lookin head ass",
		"damage": 2,
		"health": 10,
		"speed": 7,
	      },
	      {
		"level": 5,
		"upgraded": true,
		"name": "Master Genies",
		"type": "Weak ass lookin head ass",
		"damage": 2,
		"health": 10,
		"speed": 7,
	      },
	      {
		"level": 6,
		"upgraded": false,
		"name": "Nagas",
		"type": "Weak ass lookin head ass",
		"damage": 2,
		"health": 10,
		"speed": 7,
	      },
	      {
		"level": 6,
		"upgraded": true,
		"name": "Naga Queens",
		"type": "Weak ass lookin head ass",
		"damage": 2,
		"health": 10,
		"speed": 7,
	      },
	      {
		"level": 7,
		"upgraded": false,
		"name": "Giants",
		"type": "Weak ass lookin head ass",
		"damage": 2,
		"health": 10,
		"speed": 7,
	      },
	      {
		"level": 7,
		"upgraded": true,
		"name": "Titans",
		"type": "Weak ass lookin head ass",
		"damage": 2,
		"health": 10,
		"speed": 7,
	      }
	    ]
	  }
	]