let townInformation = [
  {
    "name": "Castle",
    "troops": [
      {
        "name": "Pikemen",
        "level": "1",
        "attack": "4",
        "defense": "5",
        "damage_low": "1",
        "damage_high": "3",
        "health": "10",
        "speed": "4",
        "growth": "14",
        "aiValue": "80",
        "cost": "60",
        "specials": "Immune to jousting"
      },
      {
        "name": "Halberdiers",
        "level": "1+",
        "attack": "6",
        "defense": "5",
        "damage_low": "2",
        "damage_high": "3",
        "health": "10",
        "speed": "5",
        "growth": "14",
        "aiValue": "115",
        "cost": "75",
        "specials": "Immune to jousting"
      },
      {
        "name": "Archers",
        "level": "2",
        "attack": "6",
        "defense": "3",
        "damage_low": "2",
        "damage_high": "3",
        "health": "10",
        "speed": "4",
        "growth": "9",
        "aiValue": "126",
        "cost": "100",
        "specials": "Ranged (12 shots)"
      },
      {
        "name": "Marksmen",
        "level": "2+",
        "attack": "6",
        "defense": "3",
        "damage_low": "2",
        "damage_high": "3",
        "health": "10",
        "speed": "6",
        "growth": "9",
        "aiValue": "184",
        "cost": "150",
        "specials": "Ranged (24 shots), Double attack"
      },
      {
        "name": "Griffins",
        "level": "3",
        "attack": "8",
        "defense": "8",
        "damage_low": "3",
        "damage_high": "6",
        "health": "25",
        "speed": "6",
        "growth": "7",
        "aiValue": "351",
        "cost": "200",
        "specials": "Flying, Two retaliations"
      },
      {
        "name": "Royal Griffins",
        "level": "3+",
        "attack": "9",
        "defense": "9",
        "damage_low": "3",
        "damage_high": "6",
        "health": "25",
        "speed": "9",
        "growth": "7",
        "aiValue": "448",
        "cost": "240",
        "specials": "Flying, Unlimited retaliations"
      },
      {
        "name": "Swordsmen",
        "level": "4",
        "attack": "10",
        "defense": "12",
        "damage_low": "6",
        "damage_high": "9",
        "health": "35",
        "speed": "5",
        "growth": "4",
        "aiValue": "445",
        "cost": "300",
        "specials": ""
      },
      {
        "name": "Crusaders",
        "level": "4+",
        "attack": "12",
        "defense": "12",
        "damage_low": "7",
        "damage_high": "10",
        "health": "35",
        "speed": "6",
        "growth": "4",
        "aiValue": "588",
        "cost": "400",
        "specials": "Double attack"
      },
      {
        "name": "Monks",
        "level": "5",
        "attack": "12",
        "defense": "7",
        "damage_low": "10",
        "damage_high": "12",
        "health": "30",
        "speed": "5",
        "growth": "3",
        "aiValue": "582",
        "cost": "400",
        "specials": "Ranged (12 shots)"
      },
      {
        "name": "Zealots",
        "level": "5+",
        "attack": "12",
        "defense": "10",
        "damage_low": "10",
        "damage_high": "12",
        "health": "30",
        "speed": "7",
        "growth": "3",
        "aiValue": "750",
        "cost": "450",
        "specials": "Ranged (24 shots), No melee penalty"
      },
      {
        "name": "Cavaliers",
        "level": "6",
        "attack": "15",
        "defense": "15",
        "damage_low": "15",
        "damage_high": "25",
        "health": "100",
        "speed": "7",
        "growth": "2",
        "aiValue": "1946",
        "cost": "1000",
        "specials": "Jousting"
      },
      {
        "name": "Champions",
        "level": "6+",
        "attack": "16",
        "defense": "16",
        "damage_low": "20",
        "damage_high": "25",
        "health": "100",
        "speed": "9",
        "growth": "2",
        "aiValue": "2100",
        "cost": "1200",
        "specials": "Jousting"
      },
      {
        "name": "Angels",
        "level": "7",
        "attack": "20",
        "defense": "20",
        "damage_low": "50",
        "damage_high": "50",
        "health": "200",
        "speed": "12",
        "growth": "1",
        "aiValue": "5019",
        "cost": "3000",
        "specials": "Flying, Hates Devils, Morale +1"
      },
      {
        "name": "Archangels",
        "level": "7+",
        "attack": "30",
        "defense": "30",
        "damage_low": "50",
        "damage_high": "50",
        "health": "250",
        "speed": "18",
        "growth": "1",
        "aiValue": "8776",
        "cost": "5000",
        "specials": "Flying, Hates Devils, Resurrection, Morale +1"
      }
    ]
  },
  {
    "name": "Conflux",
    "troops": [
      {
        "name": "Pixies",
        "level": "1",
        "attack": "2",
        "defense": "2",
        "damage_low": "1",
        "damage_high": "2",
        "health": "3",
        "speed": "7",
        "growth": "20",
        "aiValue": "55",
        "cost": "25",
        "specials": "Flying"
      },
      {
        "name": "Sprites",
        "level": "1+",
        "attack": "2",
        "defense": "2",
        "damage_low": "1",
        "damage_high": "3",
        "health": "3",
        "speed": "9",
        "growth": "20",
        "aiValue": "95",
        "cost": "30",
        "specials": "Flying, No enemy retaliation"
      },
      {
        "name": "Air Elementals",
        "level": "2",
        "attack": "9",
        "defense": "9",
        "damage_low": "2",
        "damage_high": "8",
        "health": "25",
        "speed": "7",
        "growth": "6",
        "aiValue": "356",
        "cost": "250",
        "specials": "Elemental, Lightning vulnerability, Immune to Meteor Shower"
      },
      {
        "name": "Storm Elementals",
        "level": "2+",
        "attack": "9",
        "defense": "9",
        "damage_low": "2",
        "damage_high": "8",
        "health": "25",
        "speed": "8",
        "growth": "6",
        "aiValue": "486",
        "cost": "275",
        "specials": "Ranged (24 shots), Elemental, Lightning vulnerability, Immune to Meteor Shower, Casts Protection from Air"
      },
      {
        "name": "Water Elementals",
        "level": "3",
        "attack": "8",
        "defense": "10",
        "damage_low": "3",
        "damage_high": "7",
        "health": "30",
        "speed": "5",
        "growth": "6",
        "aiValue": "315",
        "cost": "300",
        "specials": "Elemental, Ice immunity, Vulnerable to Fireball, Inferno and Armageddon"
      },
      {
        "name": "Ice Elementals",
        "level": "3+",
        "attack": "8",
        "defense": "10",
        "damage_low": "3",
        "damage_high": "7",
        "health": "30",
        "speed": "6",
        "growth": "6",
        "aiValue": "380",
        "cost": "375",
        "specials": "Ranged (24 shots), Elemental, Ice immunity, Vulnerable to Fireball, Inferno and Armageddon, Casts Protection from Water"
      },
      {
        "name": "Fire Elementals",
        "level": "4",
        "attack": "10",
        "defense": "8",
        "damage_low": "4",
        "damage_high": "6",
        "health": "35",
        "speed": "6",
        "growth": "5",
        "aiValue": "345",
        "cost": "350",
        "specials": "Elemental, Ice vulnerability, Fire immunity"
      },
      {
        "name": "Energy Elementals",
        "level": "4+",
        "attack": "12",
        "defense": "8",
        "damage_low": "4",
        "damage_high": "6",
        "health": "35",
        "speed": "8",
        "growth": "5",
        "aiValue": "470",
        "cost": "400",
        "specials": "Elemental, Flying, Ice vulnerability, Fire immunity, Casts Protection from Fire"
      },
      {
        "name": "Earth Elementals",
        "level": "5",
        "attack": "10",
        "defense": "10",
        "damage_low": "4",
        "damage_high": "8",
        "health": "40",
        "speed": "4",
        "growth": "4",
        "aiValue": "330",
        "cost": "400",
        "specials": "Elemental, Meteor Shower vulnerability, Lightning and Armageddon immunity"
      },
      {
        "name": "Magma Elementals",
        "level": "5+",
        "attack": "11",
        "defense": "11",
        "damage_low": "6",
        "damage_high": "10",
        "health": "40",
        "speed": "6",
        "growth": "4",
        "aiValue": "490",
        "cost": "500",
        "specials": "Elemental, Meteor Shower vulnerability, Lightning and Armageddon immunity, Casts Protection from Earth"
      },
      {
        "name": "Psychic Elementals",
        "level": "6",
        "attack": "15",
        "defense": "13",
        "damage_low": "10",
        "damage_high": "20",
        "health": "75",
        "speed": "7",
        "growth": "2",
        "aiValue": "1669",
        "cost": "950",
        "specials": "Elemental, No enemy retaliation, Attacks adjacent hexes"
      },
      {
        "name": "Magic Elementals",
        "level": "6+",
        "attack": "15",
        "defense": "13",
        "damage_low": "15",
        "damage_high": "25",
        "health": "80",
        "speed": "9",
        "growth": "2",
        "aiValue": "2012",
        "cost": "1200",
        "specials": "Elemental, No enemy retaliation, Attacks adjacent hexes, Spell immunity"
      },
      {
        "name": "Firebirds",
        "level": "7",
        "attack": "18",
        "defense": "18",
        "damage_low": "30",
        "damage_high": "40",
        "health": "150",
        "speed": "15",
        "growth": "1",
        "aiValue": "4336",
        "cost": "2000",
        "specials": "Flying, Breath attack, 50% fire resistance"
      },
      {
        "name": "Phoenixes",
        "level": "7+",
        "attack": "21",
        "defense": "18",
        "damage_low": "30",
        "damage_high": "40",
        "health": "200",
        "speed": "21",
        "growth": "1",
        "aiValue": "6721",
        "cost": "3000",
        "specials": "Flying, Breath attack, Immune to fire spells, Rebirth"
      }
    ]
  },
  {
    "name": "Cove",
    "troops": [
      {
        "name": "Nymphs",
        "level": "1",
        "attack": "5",
        "defense": "2",
        "damage_low": "1",
        "damage_high": "2",
        "health": "4",
        "speed": "6",
        "growth": "16",
        "aiValue": "57",
        "cost": "35",
        "specials": "Teleporting, Immune to ice"
      },
      {
        "name": "Oceanids",
        "level": "1+",
        "attack": "6",
        "defense": "2",
        "damage_low": "1",
        "damage_high": "3",
        "health": "4",
        "speed": "8",
        "growth": "16",
        "aiValue": "75",
        "cost": "45",
        "specials": "Teleporting, Immune to ice"
      },
      {
        "name": "Crew Mates",
        "level": "2",
        "attack": "7",
        "defense": "4",
        "damage_low": "2",
        "damage_high": "4",
        "health": "15",
        "speed": "5",
        "growth": "9",
        "aiValue": "155",
        "cost": "110",
        "specials": ""
      },
      {
        "name": "Seamen",
        "level": "2+",
        "attack": "8",
        "defense": "6",
        "damage_low": "3",
        "damage_high": "4",
        "health": "15",
        "speed": "6",
        "growth": "9",
        "aiValue": "174",
        "cost": "140",
        "specials": ""
      },
      {
        "name": "Pirates",
        "level": "3",
        "attack": "8",
        "defense": "6",
        "damage_low": "3",
        "damage_high": "7",
        "health": "15",
        "speed": "6",
        "growth": "7",
        "aiValue": "312",
        "cost": "225",
        "specials": "Ranged (4 shots)"
      },
      {
        "name": "Corsairs",
        "level": "3+",
        "attack": "10",
        "defense": "8",
        "damage_low": "3",
        "damage_high": "7",
        "health": "15",
        "speed": "7",
        "growth": "7",
        "aiValue": "407",
        "cost": "275",
        "specials": "Ranged (4 shots)"
      },
      {
        "name": "Sea Dogs",
        "level": "3++",
        "attack": "12",
        "defense": "11",
        "damage_low": "3",
        "damage_high": "7",
        "health": "15",
        "speed": "8",
        "growth": "7",
        "aiValue": "602",
        "cost": "375",
        "specials": "Ranged (12 shots), No melee penalty, No enemy retaliation, Accurate Shot"
      },
      {
        "name": "Stormbirds",
        "level": "4",
        "attack": "10",
        "defense": "8",
        "damage_low": "6",
        "damage_high": "9",
        "health": "30",
        "speed": "9",
        "growth": "4",
        "aiValue": "502",
        "cost": "275",
        "specials": "Flying"
      },
      {
        "name": "Ayssids",
        "level": "4+",
        "attack": "11",
        "defense": "8",
        "damage_low": "6",
        "damage_high": "10",
        "health": "30",
        "speed": "11",
        "growth": "4",
        "aiValue": "645",
        "cost": "325",
        "specials": "Flying, Ferocity"
      },
      {
        "name": "Sea Witches",
        "level": "5",
        "attack": "12",
        "defense": "7",
        "damage_low": "10",
        "damage_high": "14",
        "health": "35",
        "speed": "6",
        "growth": "3",
        "aiValue": "790",
        "cost": "515",
        "specials": "Ranged (12 shots), Casts Weakness / Disrupting Ray"
      },
      {
        "name": "Sorceresses",
        "level": "5+",
        "attack": "12",
        "defense": "9",
        "damage_low": "10",
        "damage_high": "16",
        "health": "35",
        "speed": "7",
        "growth": "3",
        "aiValue": "852",
        "cost": "565",
        "specials": "Ranged (12 shots), Casts Weakness / Disrupting Ray"
      },
      {
        "name": "Nix",
        "level": "6",
        "attack": "13",
        "defense": "16",
        "damage_low": "18",
        "damage_high": "22",
        "health": "80",
        "speed": "6",
        "growth": "2",
        "aiValue": "1415",
        "cost": "1000",
        "specials": "Ignores 30% of enemy attack value"
      },
      {
        "name": "Nix Warriors",
        "level": "6+",
        "attack": "14",
        "defense": "17",
        "damage_low": "18",
        "damage_high": "22",
        "health": "90",
        "speed": "7",
        "growth": "2",
        "aiValue": "2116",
        "cost": "1300",
        "specials": "Ignores 60% of enemy attack value"
      },
      {
        "name": "Sea Serpents",
        "level": "7",
        "attack": "22",
        "defense": "16",
        "damage_low": "30",
        "damage_high": "55",
        "health": "180",
        "speed": "9",
        "growth": "1",
        "aiValue": "3953",
        "cost": "2200",
        "specials": "Poisonous"
      },
      {
        "name": "Haspids",
        "level": "7+",
        "attack": "29",
        "defense": "20",
        "damage_low": "30",
        "damage_high": "55",
        "health": "300",
        "speed": "12",
        "growth": "1",
        "aiValue": "7220",
        "cost": "4000",
        "specials": "Poisonous, Revenge"
      }
    ]
  },
  {
    "name": "Dungeon",
    "troops": [
      {
        "name": "Troglodytes",
        "level": "1",
        "attack": "4",
        "defense": "3",
        "damage_low": "1",
        "damage_high": "3",
        "health": "5",
        "speed": "4",
        "growth": "14",
        "aiValue": "59",
        "cost": "50",
        "specials": "Immune to Blinding"
      },
      {
        "name": "Infernal Troglodytes",
        "level": "1+",
        "attack": "5",
        "defense": "4",
        "damage_low": "1",
        "damage_high": "3",
        "health": "6",
        "speed": "5",
        "growth": "14",
        "aiValue": "84",
        "cost": "65",
        "specials": "Immune to Blinding"
      },
      {
        "name": "Harpies",
        "level": "2",
        "attack": "6",
        "defense": "5",
        "damage_low": "1",
        "damage_high": "4",
        "health": "14",
        "speed": "6",
        "growth": "8",
        "aiValue": "154",
        "cost": "130",
        "specials": "Flying, Strike and return"
      },
      {
        "name": "Harpy Hags",
        "level": "2+",
        "attack": "6",
        "defense": "6",
        "damage_low": "1",
        "damage_high": "4",
        "health": "14",
        "speed": "9",
        "growth": "8",
        "aiValue": "238",
        "cost": "170",
        "specials": "Flying, Strike and return, No enemy retaliation"
      },
      {
        "name": "Beholders",
        "level": "3",
        "attack": "9",
        "defense": "7",
        "damage_low": "3",
        "damage_high": "5",
        "health": "22",
        "speed": "5",
        "growth": "7",
        "aiValue": "336",
        "cost": "250",
        "specials": "Ranged (12 shots), No melee penalty"
      },
      {
        "name": "Evil Eyes",
        "level": "3+",
        "attack": "10",
        "defense": "8",
        "damage_low": "3",
        "damage_high": "5",
        "health": "22",
        "speed": "7",
        "growth": "7",
        "aiValue": "367",
        "cost": "280",
        "specials": "Ranged (24 shots), No melee penalty"
      },
      {
        "name": "Medusas",
        "level": "4",
        "attack": "9",
        "defense": "9",
        "damage_low": "6",
        "damage_high": "8",
        "health": "25",
        "speed": "5",
        "growth": "4",
        "aiValue": "517",
        "cost": "300",
        "specials": "Ranged (4 shots), No melee penalty, Petrify"
      },
      {
        "name": "Medusa Queens",
        "level": "4+",
        "attack": "10",
        "defense": "10",
        "damage_low": "6",
        "damage_high": "8",
        "health": "30",
        "speed": "6",
        "growth": "4",
        "aiValue": "577",
        "cost": "330",
        "specials": "Ranged (8 shots), No melee penalty, Petrify"
      },
      {
        "name": "Minotaurs",
        "level": "5",
        "attack": "14",
        "defense": "12",
        "damage_low": "12",
        "damage_high": "20",
        "health": "50",
        "speed": "6",
        "growth": "3",
        "aiValue": "835",
        "cost": "500",
        "specials": "Positive Morale"
      },
      {
        "name": "Minotaur Kings",
        "level": "5+",
        "attack": "15",
        "defense": "15",
        "damage_low": "12",
        "damage_high": "20",
        "health": "50",
        "speed": "8",
        "growth": "3",
        "aiValue": "1068",
        "cost": "575",
        "specials": "Positive Morale"
      },
      {
        "name": "Manticores",
        "level": "6",
        "attack": "15",
        "defense": "13",
        "damage_low": "14",
        "damage_high": "20",
        "health": "80",
        "speed": "7",
        "growth": "2",
        "aiValue": "1547",
        "cost": "850",
        "specials": "Flying"
      },
      {
        "name": "Scorpicores",
        "level": "6+",
        "attack": "16",
        "defense": "14",
        "damage_low": "14",
        "damage_high": "20",
        "health": "80",
        "speed": "11",
        "growth": "2",
        "aiValue": "1589",
        "cost": "1050",
        "specials": "Flying, Paralyze"
      },
      {
        "name": "Red Dragons",
        "level": "7",
        "attack": "19",
        "defense": "19",
        "damage_low": "40",
        "damage_high": "50",
        "health": "180",
        "speed": "11",
        "growth": "1",
        "aiValue": "4702",
        "cost": "2500",
        "specials": "Dragon, Flying, Breath attack, 1-3 lvl spells immunity"
      },
      {
        "name": "Black Dragons",
        "level": "7+",
        "attack": "25",
        "defense": "25",
        "damage_low": "40",
        "damage_high": "50",
        "health": "300",
        "speed": "15",
        "growth": "1",
        "aiValue": "8721",
        "cost": "4000",
        "specials": "Dragon, Flying, Breath attack, Magic immunity, Hates Titans"
      }
    ]
  },
  {
    "name": "Fortress",
    "troops": [
      {
        "name": "Gnolls",
        "level": "1",
        "attack": "3",
        "defense": "5",
        "damage_low": "2",
        "damage_high": "3",
        "health": "6",
        "speed": "4",
        "growth": "12",
        "aiValue": "56",
        "cost": "50",
        "specials": ""
      },
      {
        "name": "Gnoll Marauders",
        "level": "1+",
        "attack": "4",
        "defense": "6",
        "damage_low": "2",
        "damage_high": "3",
        "health": "6",
        "speed": "5",
        "growth": "12",
        "aiValue": "90",
        "cost": "70",
        "specials": ""
      },
      {
        "name": "Lizardmen",
        "level": "2",
        "attack": "5",
        "defense": "6",
        "damage_low": "2",
        "damage_high": "3",
        "health": "14",
        "speed": "4",
        "growth": "9",
        "aiValue": "126",
        "cost": "110",
        "specials": "Ranged (12 shots)"
      },
      {
        "name": "Lizard Warriors",
        "level": "2+",
        "attack": "6",
        "defense": "8",
        "damage_low": "2",
        "damage_high": "5",
        "health": "15",
        "speed": "5",
        "growth": "9",
        "aiValue": "156",
        "cost": "140",
        "specials": "Ranged (24 shots)"
      },
      {
        "name": "Serpent Flies",
        "level": "3",
        "attack": "7",
        "defense": "9",
        "damage_low": "2",
        "damage_high": "5",
        "health": "20",
        "speed": "9",
        "growth": "8",
        "aiValue": "268",
        "cost": "220",
        "specials": "Flying, Dispel"
      },
      {
        "name": "Dragon Flies",
        "level": "3+",
        "attack": "8",
        "defense": "10",
        "damage_low": "2",
        "damage_high": "5",
        "health": "20",
        "speed": "13",
        "growth": "8",
        "aiValue": "312",
        "cost": "240",
        "specials": "Flying, Dispel, Weakness"
      },
      {
        "name": "Basilisks",
        "level": "4",
        "attack": "11",
        "defense": "11",
        "damage_low": "6",
        "damage_high": "10",
        "health": "35",
        "speed": "5",
        "growth": "4",
        "aiValue": "552",
        "cost": "325",
        "specials": "Petrify"
      },
      {
        "name": "Greater Basilisks",
        "level": "4+",
        "attack": "12",
        "defense": "12",
        "damage_low": "6",
        "damage_high": "10",
        "health": "40",
        "speed": "7",
        "growth": "4",
        "aiValue": "714",
        "cost": "400",
        "specials": "Petrify"
      },
      {
        "name": "Gorgons",
        "level": "5",
        "attack": "10",
        "defense": "14",
        "damage_low": "12",
        "damage_high": "16",
        "health": "70",
        "speed": "5",
        "growth": "3",
        "aiValue": "890",
        "cost": "525",
        "specials": ""
      },
      {
        "name": "Mighty Gorgons",
        "level": "5+",
        "attack": "11",
        "defense": "16",
        "damage_low": "12",
        "damage_high": "16",
        "health": "70",
        "speed": "6",
        "growth": "3",
        "aiValue": "1028",
        "cost": "600",
        "specials": "Death stare 10% chance/unit"
      },
      {
        "name": "Wyverns",
        "level": "6",
        "attack": "14",
        "defense": "14",
        "damage_low": "14",
        "damage_high": "18",
        "health": "70",
        "speed": "7",
        "growth": "2",
        "aiValue": "1350",
        "cost": "800",
        "specials": "Flying"
      },
      {
        "name": "Wyvern Monarches",
        "level": "6+",
        "attack": "14",
        "defense": "14",
        "damage_low": "18",
        "damage_high": "22",
        "health": "70",
        "speed": "11",
        "growth": "2",
        "aiValue": "1518",
        "cost": "1100",
        "specials": "Flying, Poison"
      },
      {
        "name": "Hydras",
        "level": "7",
        "attack": "16",
        "defense": "18",
        "damage_low": "25",
        "damage_high": "45",
        "health": "175",
        "speed": "5",
        "growth": "1",
        "aiValue": "4120",
        "cost": "2200",
        "specials": "No enemy retaliation, Attack all adjacent enemies"
      },
      {
        "name": "Chaos Hydras",
        "level": "7+",
        "attack": "18",
        "defense": "20",
        "damage_low": "25",
        "damage_high": "45",
        "health": "250",
        "speed": "7",
        "growth": "1",
        "aiValue": "5931",
        "cost": "3500",
        "specials": "No enemy retaliation, Attack all adjacent enemies"
      }
    ]
  },
  {
    "name": "Inferno",
    "troops": [
      {
        "name": "Imps",
        "level": "1",
        "attack": "2",
        "defense": "3",
        "damage_low": "1",
        "damage_high": "2",
        "health": "4",
        "speed": "5",
        "growth": "15",
        "aiValue": "50",
        "cost": "50",
        "specials": ""
      },
      {
        "name": "Familiars",
        "level": "1+",
        "attack": "4",
        "defense": "4",
        "damage_low": "1",
        "damage_high": "2",
        "health": "4",
        "speed": "7",
        "growth": "15",
        "aiValue": "60",
        "cost": "60",
        "specials": "Magic channel"
      },
      {
        "name": "Gogs",
        "level": "2",
        "attack": "6",
        "defense": "4",
        "damage_low": "2",
        "damage_high": "4",
        "health": "13",
        "speed": "4",
        "growth": "8",
        "aiValue": "159",
        "cost": "125",
        "specials": "Ranged (12 shots)"
      },
      {
        "name": "Magogs",
        "level": "2+",
        "attack": "7",
        "defense": "4",
        "damage_low": "2",
        "damage_high": "4",
        "health": "13",
        "speed": "6",
        "growth": "8",
        "aiValue": "240",
        "cost": "175",
        "specials": "Ranged (24 shots), Fireball attack"
      },
      {
        "name": "Hell Hounds",
        "level": "3",
        "attack": "10",
        "defense": "6",
        "damage_low": "2",
        "damage_high": "7",
        "health": "25",
        "speed": "7",
        "growth": "5",
        "aiValue": "357",
        "cost": "200",
        "specials": ""
      },
      {
        "name": "Cerberi",
        "level": "3+",
        "attack": "10",
        "defense": "8",
        "damage_low": "2",
        "damage_high": "7",
        "health": "25",
        "speed": "8",
        "growth": "5",
        "aiValue": "392",
        "cost": "250",
        "specials": "No enemy retaliation, 3-headed attack"
      },
      {
        "name": "Demons",
        "level": "4",
        "attack": "10",
        "defense": "10",
        "damage_low": "7",
        "damage_high": "9",
        "health": "35",
        "speed": "5",
        "growth": "4",
        "aiValue": "445",
        "cost": "250",
        "specials": ""
      },
      {
        "name": "Horned Demons",
        "level": "4+",
        "attack": "10",
        "defense": "10",
        "damage_low": "7",
        "damage_high": "9",
        "health": "40",
        "speed": "6",
        "growth": "4",
        "aiValue": "480",
        "cost": "270",
        "specials": ""
      },
      {
        "name": "Pit Fiends",
        "level": "5",
        "attack": "13",
        "defense": "13",
        "damage_low": "13",
        "damage_high": "17",
        "health": "45",
        "speed": "6",
        "growth": "3",
        "aiValue": "765",
        "cost": "500",
        "specials": ""
      },
      {
        "name": "Pit Lords",
        "level": "5+",
        "attack": "13",
        "defense": "13",
        "damage_low": "13",
        "damage_high": "17",
        "health": "45",
        "speed": "7",
        "growth": "3",
        "aiValue": "1224",
        "cost": "700",
        "specials": "Summon demons"
      },
      {
        "name": "Efreet",
        "level": "6",
        "attack": "16",
        "defense": "12",
        "damage_low": "16",
        "damage_high": "24",
        "health": "90",
        "speed": "9",
        "growth": "2",
        "aiValue": "1670",
        "cost": "900",
        "specials": "Flying, Fire immunity"
      },
      {
        "name": "Efreet Sultans",
        "level": "6+",
        "attack": "16",
        "defense": "14",
        "damage_low": "16",
        "damage_high": "24",
        "health": "90",
        "speed": "13",
        "growth": "2",
        "aiValue": "2343",
        "cost": "1100",
        "specials": "Flying, Fire shield, Fire immunity, Hates Genies"
      },
      {
        "name": "Devils",
        "level": "7",
        "attack": "19",
        "defense": "21",
        "damage_low": "30",
        "damage_high": "40",
        "health": "160",
        "speed": "11",
        "growth": "1",
        "aiValue": "5101",
        "cost": "2700",
        "specials": "Teleporting, No enemy retaliation, Luck -1, Hates Angels"
      },
      {
        "name": "Arch Devils",
        "level": "7+",
        "attack": "26",
        "defense": "28",
        "damage_low": "30",
        "damage_high": "40",
        "health": "200",
        "speed": "17",
        "growth": "1",
        "aiValue": "7115",
        "cost": "4500",
        "specials": "Teleporting, No enemy retaliation, Luck -2, Hates Angels"
      }
    ]
  },
  {
    "name": "Necropolis",
    "troops": [
      {
        "name": "Skeletons",
        "level": "1",
        "attack": "5",
        "defense": "4",
        "damage_low": "1",
        "damage_high": "3",
        "health": "6",
        "speed": "4",
        "growth": "12",
        "aiValue": "60",
        "cost": "60",
        "specials": "Undead"
      },
      {
        "name": "Skeleton Warriors",
        "level": "1+",
        "attack": "6",
        "defense": "6",
        "damage_low": "1",
        "damage_high": "3",
        "health": "6",
        "speed": "5",
        "growth": "12",
        "aiValue": "85",
        "cost": "70",
        "specials": "Undead"
      },
      {
        "name": "Walking Deads",
        "level": "2",
        "attack": "5",
        "defense": "5",
        "damage_low": "2",
        "damage_high": "3",
        "health": "15",
        "speed": "3",
        "growth": "8",
        "aiValue": "98",
        "cost": "100",
        "specials": "Undead"
      },
      {
        "name": "Zombies",
        "level": "2+",
        "attack": "5",
        "defense": "5",
        "damage_low": "2",
        "damage_high": "3",
        "health": "20",
        "speed": "4",
        "growth": "8",
        "aiValue": "128",
        "cost": "125",
        "specials": "Undead, Disease"
      },
      {
        "name": "Wights",
        "level": "3",
        "attack": "7",
        "defense": "7",
        "damage_low": "3",
        "damage_high": "5",
        "health": "18",
        "speed": "5",
        "growth": "7",
        "aiValue": "252",
        "cost": "200",
        "specials": "Undead, Flying, Regeneration"
      },
      {
        "name": "Wraiths",
        "level": "3+",
        "attack": "7",
        "defense": "7",
        "damage_low": "3",
        "damage_high": "5",
        "health": "18",
        "speed": "7",
        "growth": "7",
        "aiValue": "315",
        "cost": "230",
        "specials": "Undead, Flying, Regeneration, Mana drain"
      },
      {
        "name": "Vampires",
        "level": "4",
        "attack": "10",
        "defense": "9",
        "damage_low": "5",
        "damage_high": "8",
        "health": "30",
        "speed": "6",
        "growth": "4",
        "aiValue": "555",
        "cost": "360",
        "specials": "Undead, Flying, No retaliation"
      },
      {
        "name": "Vampire Lords",
        "level": "4+",
        "attack": "10",
        "defense": "10",
        "damage_low": "5",
        "damage_high": "8",
        "health": "40",
        "speed": "9",
        "growth": "4",
        "aiValue": "783",
        "cost": "500",
        "specials": "Undead, Flying, No retaliation, Life drain"
      },
      {
        "name": "Liches",
        "level": "5",
        "attack": "13",
        "defense": "10",
        "damage_low": "11",
        "damage_high": "13",
        "health": "30",
        "speed": "6",
        "growth": "3",
        "aiValue": "848",
        "cost": "550",
        "specials": "Ranged (12 shots), Undead, Death cloud"
      },
      {
        "name": "Power Liches",
        "level": "5+",
        "attack": "13",
        "defense": "10",
        "damage_low": "11",
        "damage_high": "15",
        "health": "40",
        "speed": "7",
        "growth": "3",
        "aiValue": "1079",
        "cost": "600",
        "specials": "Ranged (24 shots), Undead, Death cloud"
      },
      {
        "name": "Black Knights",
        "level": "6",
        "attack": "16",
        "defense": "16",
        "damage_low": "15",
        "damage_high": "30",
        "health": "120",
        "speed": "7",
        "growth": "2",
        "aiValue": "2087",
        "cost": "1200",
        "specials": "Undead, Curse"
      },
      {
        "name": "Dread Knights",
        "level": "6+",
        "attack": "18",
        "defense": "18",
        "damage_low": "15",
        "damage_high": "30",
        "health": "120",
        "speed": "9",
        "growth": "2",
        "aiValue": "2382",
        "cost": "1500",
        "specials": "Undead, Curse, Death blow"
      },
      {
        "name": "Bone Dragons",
        "level": "7",
        "attack": "17",
        "defense": "15",
        "damage_low": "25",
        "damage_high": "50",
        "health": "150",
        "speed": "9",
        "growth": "1",
        "aiValue": "3388",
        "cost": "1800",
        "specials": "Dragon, Undead, Flying, Morale -1"
      },
      {
        "name": "Ghost Dragons",
        "level": "7+",
        "attack": "19",
        "defense": "17",
        "damage_low": "25",
        "damage_high": "50",
        "health": "200",
        "speed": "14",
        "growth": "1",
        "aiValue": "4696",
        "cost": "3000",
        "specials": "Dragon, Undead, Flying, Morale -1, Aging"
      }
    ]
  },
  {
    "name": "Rampart",
    "troops": [
      {
        "name": "Centaurs",
        "level": "1",
        "attack": "5",
        "defense": "3",
        "damage_low": "2",
        "damage_high": "3",
        "health": "8",
        "speed": "6",
        "growth": "14",
        "aiValue": "100",
        "cost": "70",
        "specials": ""
      },
      {
        "name": "Centaur Captains",
        "level": "1+",
        "attack": "6",
        "defense": "3",
        "damage_low": "2",
        "damage_high": "3",
        "health": "10",
        "speed": "8",
        "growth": "14",
        "aiValue": "138",
        "cost": "90",
        "specials": ""
      },
      {
        "name": "Dwarves",
        "level": "2",
        "attack": "6",
        "defense": "7",
        "damage_low": "2",
        "damage_high": "4",
        "health": "20",
        "speed": "3",
        "growth": "8",
        "aiValue": "138",
        "cost": "120",
        "specials": "Resistance +20%"
      },
      {
        "name": "Battle Dwarves",
        "level": "2+",
        "attack": "7",
        "defense": "7",
        "damage_low": "2",
        "damage_high": "4",
        "health": "20",
        "speed": "5",
        "growth": "8",
        "aiValue": "209",
        "cost": "150",
        "specials": "Resistance +40%"
      },
      {
        "name": "Wood Elves",
        "level": "3",
        "attack": "9",
        "defense": "5",
        "damage_low": "3",
        "damage_high": "5",
        "health": "15",
        "speed": "6",
        "growth": "7",
        "aiValue": "234",
        "cost": "200",
        "specials": "Ranged (24 shots)"
      },
      {
        "name": "Grand Elves",
        "level": "3+",
        "attack": "9",
        "defense": "5",
        "damage_low": "3",
        "damage_high": "5",
        "health": "15",
        "speed": "7",
        "growth": "7",
        "aiValue": "331",
        "cost": "225",
        "specials": "Ranged (24 shots), Double attack"
      },
      {
        "name": "Pegasi",
        "level": "4",
        "attack": "9",
        "defense": "8",
        "damage_low": "5",
        "damage_high": "9",
        "health": "30",
        "speed": "8",
        "growth": "5",
        "aiValue": "518",
        "cost": "250",
        "specials": "Flying, Magic damper"
      },
      {
        "name": "Silver Pegasi",
        "level": "4+",
        "attack": "9",
        "defense": "10",
        "damage_low": "5",
        "damage_high": "9",
        "health": "30",
        "speed": "12",
        "growth": "5",
        "aiValue": "532",
        "cost": "275",
        "specials": "Flying, Magic damper"
      },
      {
        "name": "Dendroid Guards",
        "level": "5",
        "attack": "9",
        "defense": "12",
        "damage_low": "10",
        "damage_high": "14",
        "health": "55",
        "speed": "3",
        "growth": "3",
        "aiValue": "517",
        "cost": "350",
        "specials": "Binding"
      },
      {
        "name": "Dendroid Soldiers",
        "level": "5+",
        "attack": "9",
        "defense": "12",
        "damage_low": "10",
        "damage_high": "14",
        "health": "65",
        "speed": "4",
        "growth": "3",
        "aiValue": "803",
        "cost": "425",
        "specials": "Binding"
      },
      {
        "name": "Unicorns",
        "level": "6",
        "attack": "15",
        "defense": "14",
        "damage_low": "18",
        "damage_high": "22",
        "health": "90",
        "speed": "7",
        "growth": "2",
        "aiValue": "1806",
        "cost": "850",
        "specials": "Blind, Aura of Resistance +20%"
      },
      {
        "name": "War Unicorns",
        "level": "6+",
        "attack": "15",
        "defense": "14",
        "damage_low": "18",
        "damage_high": "22",
        "health": "110",
        "speed": "9",
        "growth": "2",
        "aiValue": "2030",
        "cost": "950",
        "specials": "Blind, Aura of Resistance +20%"
      },
      {
        "name": "Green Dragons",
        "level": "7",
        "attack": "18",
        "defense": "18",
        "damage_low": "40",
        "damage_high": "50",
        "health": "180",
        "speed": "10",
        "growth": "1",
        "aiValue": "4872",
        "cost": "2400",
        "specials": "Dragon, Flying, Breath attack, 1-3 lvl spells immunity"
      },
      {
        "name": "Gold Dragons",
        "level": "7+",
        "attack": "27",
        "defense": "27",
        "damage_low": "40",
        "damage_high": "50",
        "health": "250",
        "speed": "16",
        "growth": "1",
        "aiValue": "8613",
        "cost": "4000",
        "specials": "Dragon, Flying, Breath attack, 1-4 lvl spells immunity"
      }
    ]
  },
  {
    "name": "Stronghold",
    "troops": [
      {
        "name": "Goblins",
        "level": "1",
        "attack": "4",
        "defense": "2",
        "damage_low": "1",
        "damage_high": "2",
        "health": "5",
        "speed": "5",
        "growth": "15",
        "aiValue": "60",
        "cost": "40",
        "specials": ""
      },
      {
        "name": "Hobgoblins",
        "level": "1+",
        "attack": "5",
        "defense": "3",
        "damage_low": "1",
        "damage_high": "2",
        "health": "5",
        "speed": "7",
        "growth": "15",
        "aiValue": "78",
        "cost": "50",
        "specials": ""
      },
      {
        "name": "Wolf Riders",
        "level": "2",
        "attack": "7",
        "defense": "5",
        "damage_low": "2",
        "damage_high": "4",
        "health": "10",
        "speed": "6",
        "growth": "9",
        "aiValue": "130",
        "cost": "100",
        "specials": ""
      },
      {
        "name": "Wolf Raiders",
        "level": "2+",
        "attack": "8",
        "defense": "5",
        "damage_low": "3",
        "damage_high": "4",
        "health": "10",
        "speed": "8",
        "growth": "9",
        "aiValue": "203",
        "cost": "140",
        "specials": "Double attack"
      },
      {
        "name": "Orcs",
        "level": "3",
        "attack": "8",
        "defense": "4",
        "damage_low": "2",
        "damage_high": "5",
        "health": "15",
        "speed": "4",
        "growth": "7",
        "aiValue": "192",
        "cost": "150",
        "specials": "Ranged (12 shots)"
      },
      {
        "name": "Orc Chieftains",
        "level": "3+",
        "attack": "8",
        "defense": "4",
        "damage_low": "2",
        "damage_high": "5",
        "health": "20",
        "speed": "5",
        "growth": "7",
        "aiValue": "240",
        "cost": "165",
        "specials": "Ranged (24 shots)"
      },
      {
        "name": "Ogres",
        "level": "4",
        "attack": "13",
        "defense": "7",
        "damage_low": "6",
        "damage_high": "12",
        "health": "40",
        "speed": "4",
        "growth": "4",
        "aiValue": "416",
        "cost": "300",
        "specials": ""
      },
      {
        "name": "Ogre Magi",
        "level": "4+",
        "attack": "13",
        "defense": "7",
        "damage_low": "6",
        "damage_high": "12",
        "health": "60",
        "speed": "5",
        "growth": "4",
        "aiValue": "672",
        "cost": "400",
        "specials": "Cast Bloodlust x3"
      },
      {
        "name": "Rocs",
        "level": "5",
        "attack": "13",
        "defense": "11",
        "damage_low": "11",
        "damage_high": "15",
        "health": "60",
        "speed": "7",
        "growth": "3",
        "aiValue": "1027",
        "cost": "600",
        "specials": "Flying"
      },
      {
        "name": "Thunderbirds",
        "level": "5+",
        "attack": "13",
        "defense": "11",
        "damage_low": "11",
        "damage_high": "15",
        "health": "60",
        "speed": "11",
        "growth": "3",
        "aiValue": "1106",
        "cost": "700",
        "specials": "Flying, Lightning strike"
      },
      {
        "name": "Cyclopes",
        "level": "6",
        "attack": "15",
        "defense": "12",
        "damage_low": "16",
        "damage_high": "20",
        "health": "70",
        "speed": "6",
        "growth": "2",
        "aiValue": "1266",
        "cost": "750",
        "specials": "Ranged (16 shots), Can attack siege walls"
      },
      {
        "name": "Cyclops Kings",
        "level": "6+",
        "attack": "17",
        "defense": "13",
        "damage_low": "16",
        "damage_high": "20",
        "health": "70",
        "speed": "8",
        "growth": "2",
        "aiValue": "1443",
        "cost": "1100",
        "specials": "Ranged (24 shots), Can attack siege walls"
      },
      {
        "name": "Behemoths",
        "level": "7",
        "attack": "17",
        "defense": "17",
        "damage_low": "30",
        "damage_high": "50",
        "health": "160",
        "speed": "6",
        "growth": "1",
        "aiValue": "3162",
        "cost": "1500",
        "specials": "Defense -40% to enemy target"
      },
      {
        "name": "Ancient Behemoths",
        "level": "7+",
        "attack": "19",
        "defense": "19",
        "damage_low": "30",
        "damage_high": "50",
        "health": "300",
        "speed": "9",
        "growth": "1",
        "aiValue": "6168",
        "cost": "3000",
        "specials": "Defense -80% to enemy target"
      }
    ]
  },
  {
    "name": "Tower",
    "troops": [
      {
        "name": "Gremlins",
        "level": "1",
        "attack": "3",
        "defense": "3",
        "damage_low": "1",
        "damage_high": "2",
        "health": "4",
        "speed": "4",
        "growth": "16",
        "aiValue": "44",
        "cost": "30",
        "specials": ""
      },
      {
        "name": "Master Gremlins",
        "level": "1+",
        "attack": "4",
        "defense": "4",
        "damage_low": "1",
        "damage_high": "2",
        "health": "4",
        "speed": "5",
        "growth": "16",
        "aiValue": "66",
        "cost": "40",
        "specials": "Ranged (8 shots)"
      },
      {
        "name": "Stone Gargoyles",
        "level": "2",
        "attack": "6",
        "defense": "6",
        "damage_low": "2",
        "damage_high": "3",
        "health": "16",
        "speed": "6",
        "growth": "9",
        "aiValue": "165",
        "cost": "130",
        "specials": "Unliving, Flying"
      },
      {
        "name": "Obsidian Gargoyles",
        "level": "2+",
        "attack": "7",
        "defense": "7",
        "damage_low": "2",
        "damage_high": "3",
        "health": "16",
        "speed": "9",
        "growth": "9",
        "aiValue": "201",
        "cost": "160",
        "specials": "Unliving, Flying"
      },
      {
        "name": "Stone Golems",
        "level": "3",
        "attack": "7",
        "defense": "10",
        "damage_low": "4",
        "damage_high": "5",
        "health": "30",
        "speed": "3",
        "growth": "6",
        "aiValue": "250",
        "cost": "150",
        "specials": "Unliving, Spell Damage Resistance +50%"
      },
      {
        "name": "Iron Golems",
        "level": "3+",
        "attack": "9",
        "defense": "10",
        "damage_low": "4",
        "damage_high": "5",
        "health": "35",
        "speed": "5",
        "growth": "6",
        "aiValue": "412",
        "cost": "200",
        "specials": "Unliving, Spell Damage Resistance +75%"
      },
      {
        "name": "Magi",
        "level": "4",
        "attack": "11",
        "defense": "8",
        "damage_low": "7",
        "damage_high": "9",
        "health": "25",
        "speed": "5",
        "growth": "4",
        "aiValue": "570",
        "cost": "350",
        "specials": "Ranged (24 shots), No melee penalty, Spells cost -2 sp"
      },
      {
        "name": "Arch Magi",
        "level": "4+",
        "attack": "12",
        "defense": "9",
        "damage_low": "7",
        "damage_high": "9",
        "health": "30",
        "speed": "7",
        "growth": "4",
        "aiValue": "680",
        "cost": "450",
        "specials": "Ranged (24 shots), No melee penalty, No obstacle penalty, Spells cost -2 sp"
      },
      {
        "name": "Genies",
        "level": "5",
        "attack": "12",
        "defense": "12",
        "damage_low": "13",
        "damage_high": "16",
        "health": "40",
        "speed": "7",
        "growth": "3",
        "aiValue": "884",
        "cost": "550",
        "specials": "Flying, Hates Efreets"
      },
      {
        "name": "Master Genies",
        "level": "5+",
        "attack": "12",
        "defense": "12",
        "damage_low": "13",
        "damage_high": "16",
        "health": "40",
        "speed": "11",
        "growth": "3",
        "aiValue": "942",
        "cost": "600",
        "specials": "Flying, Spellcaster, Hates Efreets"
      },
      {
        "name": "Nagas",
        "level": "6",
        "attack": "16",
        "defense": "13",
        "damage_low": "20",
        "damage_high": "20",
        "health": "110",
        "speed": "5",
        "growth": "2",
        "aiValue": "2016",
        "cost": "1100",
        "specials": "No enemy retaliation"
      },
      {
        "name": "Naga Queens",
        "level": "6+",
        "attack": "16",
        "defense": "13",
        "damage_low": "30",
        "damage_high": "30",
        "health": "110",
        "speed": "7",
        "growth": "2",
        "aiValue": "2840",
        "cost": "1600",
        "specials": "No enemy retaliation"
      },
      {
        "name": "Giants",
        "level": "7",
        "attack": "19",
        "defense": "16",
        "damage_low": "40",
        "damage_high": "60",
        "health": "150",
        "speed": "7",
        "growth": "1",
        "aiValue": "3718",
        "cost": "2000",
        "specials": "Immunity to Mind"
      },
      {
        "name": "Titans",
        "level": "7+",
        "attack": "24",
        "defense": "24",
        "damage_low": "40",
        "damage_high": "60",
        "health": "300",
        "speed": "11",
        "growth": "1",
        "aiValue": "7500",
        "cost": "5000",
        "specials": "Ranged (24 shots), No melee penalty, Immunity to Mind, Hates Black Dragons"
      }
    ]
  }
]