let troopInformation = [
  {
    "name": "Pikemen",
    "townName": "Castle",
    "level": "1",
    "attack": 4,
    "defense": 5,
    "damage_low": 1,
    "damage_high": 3,
    "health": 10,
    "speed": 4,
    "growth": 14,
    "aiValue": 80,
    "cost": 60,
    "specials": "Immune to jousting",
    "imageSrc": "./img/Castle/Pikemen.PNG",
    "damage": "1-3",
    "archerDamage": 0,
    "type": ""
  },
  {
    "name": "Halberdiers",
    "townName": "Castle",
    "level": "1+",
    "attack": 6,
    "defense": 5,
    "damage_low": 2,
    "damage_high": 3,
    "health": 10,
    "speed": 5,
    "growth": 14,
    "aiValue": 115,
    "cost": 75,
    "specials": "Immune to jousting",
    "imageSrc": "./img/Castle/Halberdiers.PNG",
    "damage": "2-3",
    "archerDamage": 0,
    "type": ""
  },
  {
    "name": "Archers",
    "townName": "Castle",
    "level": "2",
    "attack": 6,
    "defense": 3,
    "damage_low": 2,
    "damage_high": 3,
    "health": 10,
    "speed": 4,
    "growth": 9,
    "aiValue": 126,
    "cost": 100,
    "specials": "Ranged (12 shots)",
    "imageSrc": "./img/Castle/Archers.PNG",
    "damage": "2-3",
    "archerDamage": 12,
    "type": "Archer (12dmg)"
  },
  {
    "name": "Marksmen",
    "townName": "Castle",
    "level": "2+",
    "attack": 6,
    "defense": 3,
    "damage_low": 2,
    "damage_high": 3,
    "health": 10,
    "speed": 6,
    "growth": 9,
    "aiValue": 184,
    "cost": 150,
    "specials": "Ranged (24 shots), Double attack",
    "imageSrc": "./img/Castle/Marksmen.PNG",
    "damage": "2-3",
    "archerDamage": 24,
    "type": "Archer (24dmg)"
  },
  {
    "name": "Griffins",
    "townName": "Castle",
    "level": "3",
    "attack": 8,
    "defense": 8,
    "damage_low": 3,
    "damage_high": 6,
    "health": 25,
    "speed": 6,
    "growth": 7,
    "aiValue": 351,
    "cost": 200,
    "specials": "Flying, Two retaliations",
    "imageSrc": "./img/Castle/Griffins.PNG",
    "damage": "3-6",
    "archerDamage": 0,
    "type": ""
  },
  {
    "name": "Royal Griffins",
    "townName": "Castle",
    "level": "3+",
    "attack": 9,
    "defense": 9,
    "damage_low": 3,
    "damage_high": 6,
    "health": 25,
    "speed": 9,
    "growth": 7,
    "aiValue": 448,
    "cost": 240,
    "specials": "Flying, Unlimited retaliations",
    "imageSrc": "./img/Castle/Royal Griffins.PNG",
    "damage": "3-6",
    "archerDamage": 0,
    "type": "Fast"
  },
  {
    "name": "Swordsmen",
    "townName": "Castle",
    "level": "4",
    "attack": 10,
    "defense": 12,
    "damage_low": 6,
    "damage_high": 9,
    "health": 35,
    "speed": 5,
    "growth": 4,
    "aiValue": 445,
    "cost": 300,
    "specials": "",
    "imageSrc": "./img/Castle/Swordsmen.PNG",
    "damage": "6-9",
    "archerDamage": 0,
    "type": ""
  },
  {
    "name": "Crusaders",
    "townName": "Castle",
    "level": "4+",
    "attack": 12,
    "defense": 12,
    "damage_low": 7,
    "damage_high": 10,
    "health": 35,
    "speed": 6,
    "growth": 4,
    "aiValue": 588,
    "cost": 400,
    "specials": "Double attack",
    "imageSrc": "./img/Castle/Crusaders.PNG",
    "damage": "7-10",
    "archerDamage": 0,
    "type": ""
  },
  {
    "name": "Monks",
    "townName": "Castle",
    "level": "5",
    "attack": 12,
    "defense": 7,
    "damage_low": 10,
    "damage_high": 12,
    "health": 30,
    "speed": 5,
    "growth": 3,
    "aiValue": 582,
    "cost": 400,
    "specials": "Ranged (12 shots)",
    "imageSrc": "./img/Castle/Monks.PNG",
    "damage": "10-12",
    "archerDamage": 12,
    "type": "Archer (12dmg)"
  },
  {
    "name": "Zealots",
    "townName": "Castle",
    "level": "5+",
    "attack": 12,
    "defense": 10,
    "damage_low": 10,
    "damage_high": 12,
    "health": 30,
    "speed": 7,
    "growth": 3,
    "aiValue": 750,
    "cost": 450,
    "specials": "Ranged (24 shots), No melee penalty",
    "imageSrc": "./img/Castle/Zealots.PNG",
    "damage": "10-12",
    "archerDamage": 24,
    "type": "Archer (24dmg) Fast"
  },
  {
    "name": "Cavaliers",
    "townName": "Castle",
    "level": "6",
    "attack": 15,
    "defense": 15,
    "damage_low": 15,
    "damage_high": 25,
    "health": 100,
    "speed": 7,
    "growth": 2,
    "aiValue": 1946,
    "cost": 1000,
    "specials": "Jousting",
    "imageSrc": "./img/Castle/Cavaliers.PNG",
    "damage": "15-25",
    "archerDamage": 0,
    "type": "Fast Tank"
  },
  {
    "name": "Champions",
    "townName": "Castle",
    "level": "6+",
    "attack": 16,
    "defense": 16,
    "damage_low": 20,
    "damage_high": 25,
    "health": 100,
    "speed": 9,
    "growth": 2,
    "aiValue": 2100,
    "cost": 1200,
    "specials": "Jousting",
    "imageSrc": "./img/Castle/Champions.PNG",
    "damage": "20-25",
    "archerDamage": 0,
    "type": "Fast Tank"
  },
  {
    "name": "Angels",
    "townName": "Castle",
    "level": "7",
    "attack": 20,
    "defense": 20,
    "damage_low": 50,
    "damage_high": 50,
    "health": 200,
    "speed": 12,
    "growth": 1,
    "aiValue": 5019,
    "cost": 3000,
    "specials": "Flying, Hates Devils, Morale +1",
    "imageSrc": "./img/Castle/Angels.PNG",
    "damage": "50-50",
    "archerDamage": 0,
    "type": "Fast Tank"
  },
  {
    "name": "Archangels",
    "townName": "Castle",
    "level": "7+",
    "attack": 30,
    "defense": 30,
    "damage_low": 50,
    "damage_high": 50,
    "health": 250,
    "speed": 18,
    "growth": 1,
    "aiValue": 8776,
    "cost": 5000,
    "specials": "Flying, Hates Devils, Resurrection, Morale +1",
    "imageSrc": "./img/Castle/Archangels.PNG",
    "damage": "50-50",
    "archerDamage": 0,
    "type": "Fast Tank"
  },
  {
    "name": "Pixies",
    "townName": "Conflux",
    "level": "1",
    "attack": 2,
    "defense": 2,
    "damage_low": 1,
    "damage_high": 2,
    "health": 3,
    "speed": 7,
    "growth": 20,
    "aiValue": 55,
    "cost": 25,
    "specials": "Flying",
    "imageSrc": "./img/Conflux/Pixies.PNG",
    "damage": "1-2",
    "archerDamage": 0,
    "type": "Fast"
  },
  {
    "name": "Sprites",
    "townName": "Conflux",
    "level": "1+",
    "attack": 2,
    "defense": 2,
    "damage_low": 1,
    "damage_high": 3,
    "health": 3,
    "speed": 9,
    "growth": 20,
    "aiValue": 95,
    "cost": 30,
    "specials": "Flying, No enemy retaliation",
    "imageSrc": "./img/Conflux/Sprites.PNG",
    "damage": "1-3",
    "archerDamage": 0,
    "type": "Fast"
  },
  {
    "name": "Air Elementals",
    "townName": "Conflux",
    "level": "2",
    "attack": 9,
    "defense": 9,
    "damage_low": 2,
    "damage_high": 8,
    "health": 25,
    "speed": 7,
    "growth": 6,
    "aiValue": 356,
    "cost": 250,
    "specials": "Elemental, Lightning vulnerability, Immune to Meteor Shower",
    "imageSrc": "./img/Conflux/Air Elementals.PNG",
    "damage": "2-8",
    "archerDamage": 0,
    "type": "Fast"
  },
  {
    "name": "Storm Elementals",
    "townName": "Conflux",
    "level": "2+",
    "attack": 9,
    "defense": 9,
    "damage_low": 2,
    "damage_high": 8,
    "health": 25,
    "speed": 8,
    "growth": 6,
    "aiValue": 486,
    "cost": 275,
    "specials": "Ranged (24 shots), Elemental, Lightning vulnerability, Immune to Meteor Shower, Casts Protection from Air",
    "imageSrc": "./img/Conflux/Storm Elementals.PNG",
    "damage": "2-8",
    "archerDamage": 24,
    "type": "Archer (24dmg) Fast"
  },
  {
    "name": "Water Elementals",
    "townName": "Conflux",
    "level": "3",
    "attack": 8,
    "defense": 10,
    "damage_low": 3,
    "damage_high": 7,
    "health": 30,
    "speed": 5,
    "growth": 6,
    "aiValue": 315,
    "cost": 300,
    "specials": "Elemental, Ice immunity, Vulnerable to Fireball, Inferno and Armageddon",
    "imageSrc": "./img/Conflux/Water Elementals.PNG",
    "damage": "3-7",
    "archerDamage": 0,
    "type": ""
  },
  {
    "name": "Ice Elementals",
    "townName": "Conflux",
    "level": "3+",
    "attack": 8,
    "defense": 10,
    "damage_low": 3,
    "damage_high": 7,
    "health": 30,
    "speed": 6,
    "growth": 6,
    "aiValue": 380,
    "cost": 375,
    "specials": "Ranged (24 shots), Elemental, Ice immunity, Vulnerable to Fireball, Inferno and Armageddon, Casts Protection from Water",
    "imageSrc": "./img/Conflux/Ice Elementals.PNG",
    "damage": "3-7",
    "archerDamage": 24,
    "type": "Archer (24dmg)"
  },
  {
    "name": "Fire Elementals",
    "townName": "Conflux",
    "level": "4",
    "attack": 10,
    "defense": 8,
    "damage_low": 4,
    "damage_high": 6,
    "health": 35,
    "speed": 6,
    "growth": 5,
    "aiValue": 345,
    "cost": 350,
    "specials": "Elemental, Ice vulnerability, Fire immunity",
    "imageSrc": "./img/Conflux/Fire Elementals.PNG",
    "damage": "4-6",
    "archerDamage": 0,
    "type": ""
  },
  {
    "name": "Energy Elementals",
    "townName": "Conflux",
    "level": "4+",
    "attack": 12,
    "defense": 8,
    "damage_low": 4,
    "damage_high": 6,
    "health": 35,
    "speed": 8,
    "growth": 5,
    "aiValue": 470,
    "cost": 400,
    "specials": "Elemental, Flying, Ice vulnerability, Fire immunity, Casts Protection from Fire",
    "imageSrc": "./img/Conflux/Energy Elementals.PNG",
    "damage": "4-6",
    "archerDamage": 0,
    "type": "Fast"
  },
  {
    "name": "Earth Elementals",
    "townName": "Conflux",
    "level": "5",
    "attack": 10,
    "defense": 10,
    "damage_low": 4,
    "damage_high": 8,
    "health": 40,
    "speed": 4,
    "growth": 4,
    "aiValue": 330,
    "cost": 400,
    "specials": "Elemental, Meteor Shower vulnerability, Lightning and Armageddon immunity",
    "imageSrc": "./img/Conflux/Earth Elementals.PNG",
    "damage": "4-8",
    "archerDamage": 0,
    "type": ""
  },
  {
    "name": "Magma Elementals",
    "townName": "Conflux",
    "level": "5+",
    "attack": 11,
    "defense": 11,
    "damage_low": 6,
    "damage_high": 10,
    "health": 40,
    "speed": 6,
    "growth": 4,
    "aiValue": 490,
    "cost": 500,
    "specials": "Elemental, Meteor Shower vulnerability, Lightning and Armageddon immunity, Casts Protection from Earth",
    "imageSrc": "./img/Conflux/Magma Elementals.PNG",
    "damage": "6-10",
    "archerDamage": 0,
    "type": ""
  },
  {
    "name": "Psychic Elementals",
    "townName": "Conflux",
    "level": "6",
    "attack": 15,
    "defense": 13,
    "damage_low": 10,
    "damage_high": 20,
    "health": 75,
    "speed": 7,
    "growth": 2,
    "aiValue": 1669,
    "cost": 950,
    "specials": "Elemental, No enemy retaliation, Attacks adjacent hexes",
    "imageSrc": "./img/Conflux/Psychic Elementals.PNG",
    "damage": "10-20",
    "archerDamage": 0,
    "type": "Fast Tank"
  },
  {
    "name": "Magic Elementals",
    "townName": "Conflux",
    "level": "6+",
    "attack": 15,
    "defense": 13,
    "damage_low": 15,
    "damage_high": 25,
    "health": 80,
    "speed": 9,
    "growth": 2,
    "aiValue": 2012,
    "cost": 1200,
    "specials": "Elemental, No enemy retaliation, Attacks adjacent hexes, Spell immunity",
    "imageSrc": "./img/Conflux/Magic Elementals.PNG",
    "damage": "15-25",
    "archerDamage": 0,
    "type": "Fast Tank"
  },
  {
    "name": "Firebirds",
    "townName": "Conflux",
    "level": "7",
    "attack": 18,
    "defense": 18,
    "damage_low": 30,
    "damage_high": 40,
    "health": 150,
    "speed": 15,
    "growth": 1,
    "aiValue": 4336,
    "cost": 2000,
    "specials": "Flying, Breath attack, 50% fire resistance",
    "imageSrc": "./img/Conflux/Firebirds.PNG",
    "damage": "30-40",
    "archerDamage": 0,
    "type": "Fast Tank"
  },
  {
    "name": "Phoenixes",
    "townName": "Conflux",
    "level": "7+",
    "attack": 21,
    "defense": 18,
    "damage_low": 30,
    "damage_high": 40,
    "health": 200,
    "speed": 21,
    "growth": 1,
    "aiValue": 6721,
    "cost": 3000,
    "specials": "Flying, Breath attack, Immune to fire spells, Rebirth",
    "imageSrc": "./img/Conflux/Phoenixes.PNG",
    "damage": "30-40",
    "archerDamage": 0,
    "type": "Fast Tank"
  },
  {
    "name": "Nymphs",
    "townName": "Cove",
    "level": "1",
    "attack": 5,
    "defense": 2,
    "damage_low": 1,
    "damage_high": 2,
    "health": 4,
    "speed": 6,
    "growth": 16,
    "aiValue": 57,
    "cost": 35,
    "specials": "Teleporting, Immune to ice",
    "imageSrc": "./img/Cove/Nymphs.PNG",
    "damage": "1-2",
    "archerDamage": 0,
    "type": "Weak"
  },
  {
    "name": "Oceanids",
    "townName": "Cove",
    "level": "1+",
    "attack": 6,
    "defense": 2,
    "damage_low": 1,
    "damage_high": 3,
    "health": 4,
    "speed": 8,
    "growth": 16,
    "aiValue": 75,
    "cost": 45,
    "specials": "Teleporting, Immune to ice",
    "imageSrc": "./img/Cove/Oceanids.PNG",
    "damage": "1-3",
    "archerDamage": 0,
    "type": "Fast"
  },
  {
    "name": "Crew Mates",
    "townName": "Cove",
    "level": "2",
    "attack": 7,
    "defense": 4,
    "damage_low": 2,
    "damage_high": 4,
    "health": 15,
    "speed": 5,
    "growth": 9,
    "aiValue": 155,
    "cost": 110,
    "specials": "",
    "imageSrc": "./img/Cove/Crew Mates.PNG",
    "damage": "2-4",
    "archerDamage": 0,
    "type": ""
  },
  {
    "name": "Seamen",
    "townName": "Cove",
    "level": "2+",
    "attack": 8,
    "defense": 6,
    "damage_low": 3,
    "damage_high": 4,
    "health": 15,
    "speed": 6,
    "growth": 9,
    "aiValue": 174,
    "cost": 140,
    "specials": "",
    "imageSrc": "./img/Cove/Seamen.PNG",
    "damage": "3-4",
    "archerDamage": 0,
    "type": ""
  },
  {
    "name": "Pirates",
    "townName": "Cove",
    "level": "3",
    "attack": 8,
    "defense": 6,
    "damage_low": 3,
    "damage_high": 7,
    "health": 15,
    "speed": 6,
    "growth": 7,
    "aiValue": 312,
    "cost": 225,
    "specials": "Ranged (4 shots)",
    "imageSrc": "./img/Cove/Pirates.PNG",
    "damage": "3-7",
    "archerDamage": 4,
    "type": "Archer (4dmg)"
  },
  {
    "name": "Corsairs",
    "townName": "Cove",
    "level": "3+",
    "attack": 10,
    "defense": 8,
    "damage_low": 3,
    "damage_high": 7,
    "health": 15,
    "speed": 7,
    "growth": 7,
    "aiValue": 407,
    "cost": 275,
    "specials": "Ranged (4 shots)",
    "imageSrc": "./img/Cove/Corsairs.PNG",
    "damage": "3-7",
    "archerDamage": 4,
    "type": "Archer (4dmg) Fast"
  },
  {
    "name": "Sea Dogs",
    "townName": "Cove",
    "level": "3++",
    "attack": 12,
    "defense": 11,
    "damage_low": 3,
    "damage_high": 7,
    "health": 15,
    "speed": 8,
    "growth": 7,
    "aiValue": 602,
    "cost": 375,
    "specials": "Ranged (12 shots), No melee penalty, No enemy retaliation, Accurate Shot",
    "imageSrc": "./img/Cove/Sea Dogs.PNG",
    "damage": "3-7",
    "archerDamage": 12,
    "type": "Archer (12dmg) Fast"
  },
  {
    "name": "Stormbirds",
    "townName": "Cove",
    "level": "4",
    "attack": 10,
    "defense": 8,
    "damage_low": 6,
    "damage_high": 9,
    "health": 30,
    "speed": 9,
    "growth": 4,
    "aiValue": 502,
    "cost": 275,
    "specials": "Flying",
    "imageSrc": "./img/Cove/Stormbirds.PNG",
    "damage": "6-9",
    "archerDamage": 0,
    "type": "Fast"
  },
  {
    "name": "Ayssids",
    "townName": "Cove",
    "level": "4+",
    "attack": 11,
    "defense": 8,
    "damage_low": 6,
    "damage_high": 10,
    "health": 30,
    "speed": 11,
    "growth": 4,
    "aiValue": 645,
    "cost": 325,
    "specials": "Flying, Ferocity",
    "imageSrc": "./img/Cove/Ayssids.PNG",
    "damage": "6-10",
    "archerDamage": 0,
    "type": "Fast"
  },
  {
    "name": "Sea Witches",
    "townName": "Cove",
    "level": "5",
    "attack": 12,
    "defense": 7,
    "damage_low": 10,
    "damage_high": 14,
    "health": 35,
    "speed": 6,
    "growth": 3,
    "aiValue": 790,
    "cost": 515,
    "specials": "Ranged (12 shots), Casts Weakness / Disrupting Ray",
    "imageSrc": "./img/Cove/Sea Witches.PNG",
    "damage": "10-14",
    "archerDamage": 12,
    "type": "Archer (12dmg)"
  },
  {
    "name": "Sorceresses",
    "townName": "Cove",
    "level": "5+",
    "attack": 12,
    "defense": 9,
    "damage_low": 10,
    "damage_high": 16,
    "health": 35,
    "speed": 7,
    "growth": 3,
    "aiValue": 852,
    "cost": 565,
    "specials": "Ranged (12 shots), Casts Weakness / Disrupting Ray",
    "imageSrc": "./img/Cove/Sorceresses.PNG",
    "damage": "10-16",
    "archerDamage": 12,
    "type": "Archer (12dmg) Fast"
  },
  {
    "name": "Nixes",
    "townName": "Cove",
    "level": "6",
    "attack": 13,
    "defense": 16,
    "damage_low": 18,
    "damage_high": 22,
    "health": 80,
    "speed": 6,
    "growth": 2,
    "aiValue": 1415,
    "cost": 1000,
    "specials": "Ignores 30% of enemy attack value",
    "imageSrc": "./img/Cove/Nixes.PNG",
    "damage": "18-22",
    "archerDamage": 0,
    "type": "Tank"
  },
  {
    "name": "Nix Warriors",
    "townName": "Cove",
    "level": "6+",
    "attack": 14,
    "defense": 17,
    "damage_low": 18,
    "damage_high": 22,
    "health": 90,
    "speed": 7,
    "growth": 2,
    "aiValue": 2116,
    "cost": 1300,
    "specials": "Ignores 60% of enemy attack value",
    "imageSrc": "./img/Cove/Nix Warriors.PNG",
    "damage": "18-22",
    "archerDamage": 0,
    "type": "Fast Tank"
  },
  {
    "name": "Sea Serpents",
    "townName": "Cove",
    "level": "7",
    "attack": 22,
    "defense": 16,
    "damage_low": 30,
    "damage_high": 55,
    "health": 180,
    "speed": 9,
    "growth": 1,
    "aiValue": 3953,
    "cost": 2200,
    "specials": "Poisonous",
    "imageSrc": "./img/Cove/Sea Serpents.PNG",
    "damage": "30-55",
    "archerDamage": 0,
    "type": "Fast Tank"
  },
  {
    "name": "Haspids",
    "townName": "Cove",
    "level": "7+",
    "attack": 29,
    "defense": 20,
    "damage_low": 30,
    "damage_high": 55,
    "health": 300,
    "speed": 12,
    "growth": 1,
    "aiValue": 7220,
    "cost": 4000,
    "specials": "Poisonous, Revenge",
    "imageSrc": "./img/Cove/Haspids.PNG",
    "damage": "30-55",
    "archerDamage": 0,
    "type": "Fast Tank"
  },
  {
    "name": "Troglodytes",
    "townName": "Dungeon",
    "level": "1",
    "attack": 4,
    "defense": 3,
    "damage_low": 1,
    "damage_high": 3,
    "health": 5,
    "speed": 4,
    "growth": 14,
    "aiValue": 59,
    "cost": 50,
    "specials": "Immune to Blinding",
    "imageSrc": "./img/Dungeon/Troglodytes.PNG",
    "damage": "1-3",
    "archerDamage": 0,
    "type": "Weak"
  },
  {
    "name": "Infernal Troglodytes",
    "townName": "Dungeon",
    "level": "1+",
    "attack": 5,
    "defense": 4,
    "damage_low": 1,
    "damage_high": 3,
    "health": 6,
    "speed": 5,
    "growth": 14,
    "aiValue": 84,
    "cost": 65,
    "specials": "Immune to Blinding",
    "imageSrc": "./img/Dungeon/Infernal Troglodytes.PNG",
    "damage": "1-3",
    "archerDamage": 0,
    "type": "Weak"
  },
  {
    "name": "Harpys",
    "townName": "Dungeon",
    "level": "2",
    "attack": 6,
    "defense": 5,
    "damage_low": 1,
    "damage_high": 4,
    "health": 14,
    "speed": 6,
    "growth": 8,
    "aiValue": 154,
    "cost": 130,
    "specials": "Flying, Strike and return",
    "imageSrc": "./img/Dungeon/Harpys.PNG",
    "damage": "1-4",
    "archerDamage": 0,
    "type": ""
  },
  {
    "name": "Harpy Hags",
    "townName": "Dungeon",
    "level": "2+",
    "attack": 6,
    "defense": 6,
    "damage_low": 1,
    "damage_high": 4,
    "health": 14,
    "speed": 9,
    "growth": 8,
    "aiValue": 238,
    "cost": 170,
    "specials": "Flying, Strike and return, No enemy retaliation",
    "imageSrc": "./img/Dungeon/Harpy Hags.PNG",
    "damage": "1-4",
    "archerDamage": 0,
    "type": "Fast"
  },
  {
    "name": "Beholders",
    "townName": "Dungeon",
    "level": "3",
    "attack": 9,
    "defense": 7,
    "damage_low": 3,
    "damage_high": 5,
    "health": 22,
    "speed": 5,
    "growth": 7,
    "aiValue": 336,
    "cost": 250,
    "specials": "Ranged (12 shots), No melee penalty",
    "imageSrc": "./img/Dungeon/Beholders.PNG",
    "damage": "3-5",
    "archerDamage": 12,
    "type": "Archer (12dmg)"
  },
  {
    "name": "Evil Eyes",
    "townName": "Dungeon",
    "level": "3+",
    "attack": 10,
    "defense": 8,
    "damage_low": 3,
    "damage_high": 5,
    "health": 22,
    "speed": 7,
    "growth": 7,
    "aiValue": 367,
    "cost": 280,
    "specials": "Ranged (24 shots), No melee penalty",
    "imageSrc": "./img/Dungeon/Evil Eyes.PNG",
    "damage": "3-5",
    "archerDamage": 24,
    "type": "Archer (24dmg) Fast"
  },
  {
    "name": "Medusas",
    "townName": "Dungeon",
    "level": "4",
    "attack": 9,
    "defense": 9,
    "damage_low": 6,
    "damage_high": 8,
    "health": 25,
    "speed": 5,
    "growth": 4,
    "aiValue": 517,
    "cost": 300,
    "specials": "Ranged (4 shots), No melee penalty, Petrify",
    "imageSrc": "./img/Dungeon/Medusas.PNG",
    "damage": "6-8",
    "archerDamage": 4,
    "type": "Archer (4dmg)"
  },
  {
    "name": "Medusa Queens",
    "townName": "Dungeon",
    "level": "4+",
    "attack": 10,
    "defense": 10,
    "damage_low": 6,
    "damage_high": 8,
    "health": 30,
    "speed": 6,
    "growth": 4,
    "aiValue": 577,
    "cost": 330,
    "specials": "Ranged (8 shots), No melee penalty, Petrify",
    "imageSrc": "./img/Dungeon/Medusa Queens.PNG",
    "damage": "6-8",
    "archerDamage": 8,
    "type": "Archer (8dmg)"
  },
  {
    "name": "Minotaurs",
    "townName": "Dungeon",
    "level": "5",
    "attack": 14,
    "defense": 12,
    "damage_low": 12,
    "damage_high": 20,
    "health": 50,
    "speed": 6,
    "growth": 3,
    "aiValue": 835,
    "cost": 500,
    "specials": "Positive Morale",
    "imageSrc": "./img/Dungeon/Minotaurs.PNG",
    "damage": "12-20",
    "archerDamage": 0,
    "type": ""
  },
  {
    "name": "Minotaur Kings",
    "townName": "Dungeon",
    "level": "5+",
    "attack": 15,
    "defense": 15,
    "damage_low": 12,
    "damage_high": 20,
    "health": 50,
    "speed": 8,
    "growth": 3,
    "aiValue": 1068,
    "cost": 575,
    "specials": "Positive Morale",
    "imageSrc": "./img/Dungeon/Minotaur Kings.PNG",
    "damage": "12-20",
    "archerDamage": 0,
    "type": "Fast"
  },
  {
    "name": "Manticores",
    "townName": "Dungeon",
    "level": "6",
    "attack": 15,
    "defense": 13,
    "damage_low": 14,
    "damage_high": 20,
    "health": 80,
    "speed": 7,
    "growth": 2,
    "aiValue": 1547,
    "cost": 850,
    "specials": "Flying",
    "imageSrc": "./img/Dungeon/Manticores.PNG",
    "damage": "14-20",
    "archerDamage": 0,
    "type": "Fast Tank"
  },
  {
    "name": "Scorpicores",
    "townName": "Dungeon",
    "level": "6+",
    "attack": 16,
    "defense": 14,
    "damage_low": 14,
    "damage_high": 20,
    "health": 80,
    "speed": 11,
    "growth": 2,
    "aiValue": 1589,
    "cost": 1050,
    "specials": "Flying, Paralyze",
    "imageSrc": "./img/Dungeon/Scorpicores.PNG",
    "damage": "14-20",
    "archerDamage": 0,
    "type": "Fast Tank"
  },
  {
    "name": "Red Dragons",
    "townName": "Dungeon",
    "level": "7",
    "attack": 19,
    "defense": 19,
    "damage_low": 40,
    "damage_high": 50,
    "health": 180,
    "speed": 11,
    "growth": 1,
    "aiValue": 4702,
    "cost": 2500,
    "specials": "Dragon, Flying, Breath attack, 1-3 lvl spells immunity",
    "imageSrc": "./img/Dungeon/Red Dragons.PNG",
    "damage": "40-50",
    "archerDamage": 0,
    "type": "Fast Tank"
  },
  {
    "name": "Black Dragons",
    "townName": "Dungeon",
    "level": "7+",
    "attack": 25,
    "defense": 25,
    "damage_low": 40,
    "damage_high": 50,
    "health": 300,
    "speed": 15,
    "growth": 1,
    "aiValue": 8721,
    "cost": 4000,
    "specials": "Dragon, Flying, Breath attack, Magic immunity, Hates Titans",
    "imageSrc": "./img/Dungeon/Black Dragons.PNG",
    "damage": "40-50",
    "archerDamage": 0,
    "type": "Fast Tank"
  },
  {
    "name": "Gnolls",
    "townName": "Fortress",
    "level": "1",
    "attack": 3,
    "defense": 5,
    "damage_low": 2,
    "damage_high": 3,
    "health": 6,
    "speed": 4,
    "growth": 12,
    "aiValue": 56,
    "cost": 50,
    "specials": "",
    "imageSrc": "./img/Fortress/Gnolls.PNG",
    "damage": "2-3",
    "archerDamage": 0,
    "type": "Weak"
  },
  {
    "name": "Gnoll Marauders",
    "townName": "Fortress",
    "level": "1+",
    "attack": 4,
    "defense": 6,
    "damage_low": 2,
    "damage_high": 3,
    "health": 6,
    "speed": 5,
    "growth": 12,
    "aiValue": 90,
    "cost": 70,
    "specials": "",
    "imageSrc": "./img/Fortress/Gnoll Marauders.PNG",
    "damage": "2-3",
    "archerDamage": 0,
    "type": "Weak"
  },
  {
    "name": "Lizardmen",
    "townName": "Fortress",
    "level": "2",
    "attack": 5,
    "defense": 6,
    "damage_low": 2,
    "damage_high": 3,
    "health": 14,
    "speed": 4,
    "growth": 9,
    "aiValue": 126,
    "cost": 110,
    "specials": "Ranged (12 shots)",
    "imageSrc": "./img/Fortress/Lizardmen.PNG",
    "damage": "2-3",
    "archerDamage": 12,
    "type": "Archer (12dmg)"
  },
  {
    "name": "Lizard Warriors",
    "townName": "Fortress",
    "level": "2+",
    "attack": 6,
    "defense": 8,
    "damage_low": 2,
    "damage_high": 5,
    "health": 15,
    "speed": 5,
    "growth": 9,
    "aiValue": 156,
    "cost": 140,
    "specials": "Ranged (24 shots)",
    "imageSrc": "./img/Fortress/Lizard Warriors.PNG",
    "damage": "2-5",
    "archerDamage": 24,
    "type": "Archer (24dmg)"
  },
  {
    "name": "Serpent Flys",
    "townName": "Fortress",
    "level": "3",
    "attack": 7,
    "defense": 9,
    "damage_low": 2,
    "damage_high": 5,
    "health": 20,
    "speed": 9,
    "growth": 8,
    "aiValue": 268,
    "cost": 220,
    "specials": "Flying, Dispel",
    "imageSrc": "./img/Fortress/Serpent Flys.PNG",
    "damage": "2-5",
    "archerDamage": 0,
    "type": "Fast"
  },
  {
    "name": "Dragon Flys",
    "townName": "Fortress",
    "level": "3+",
    "attack": 8,
    "defense": 10,
    "damage_low": 2,
    "damage_high": 5,
    "health": 20,
    "speed": 13,
    "growth": 8,
    "aiValue": 312,
    "cost": 240,
    "specials": "Flying, Dispel, Weakness",
    "imageSrc": "./img/Fortress/Dragon Flys.PNG",
    "damage": "2-5",
    "archerDamage": 0,
    "type": "Fast"
  },
  {
    "name": "Basilisks",
    "townName": "Fortress",
    "level": "4",
    "attack": 11,
    "defense": 11,
    "damage_low": 6,
    "damage_high": 10,
    "health": 35,
    "speed": 5,
    "growth": 4,
    "aiValue": 552,
    "cost": 325,
    "specials": "Petrify",
    "imageSrc": "./img/Fortress/Basilisks.PNG",
    "damage": "6-10",
    "archerDamage": 0,
    "type": ""
  },
  {
    "name": "Greater Basilisks",
    "townName": "Fortress",
    "level": "4+",
    "attack": 12,
    "defense": 12,
    "damage_low": 6,
    "damage_high": 10,
    "health": 40,
    "speed": 7,
    "growth": 4,
    "aiValue": 714,
    "cost": 400,
    "specials": "Petrify",
    "imageSrc": "./img/Fortress/Greater Basilisks.PNG",
    "damage": "6-10",
    "archerDamage": 0,
    "type": "Fast"
  },
  {
    "name": "Gorgons",
    "townName": "Fortress",
    "level": "5",
    "attack": 10,
    "defense": 14,
    "damage_low": 12,
    "damage_high": 16,
    "health": 70,
    "speed": 5,
    "growth": 3,
    "aiValue": 890,
    "cost": 525,
    "specials": "",
    "imageSrc": "./img/Fortress/Gorgons.PNG",
    "damage": "12-16",
    "archerDamage": 0,
    "type": "Tank"
  },
  {
    "name": "Mighty Gorgons",
    "townName": "Fortress",
    "level": "5+",
    "attack": 11,
    "defense": 16,
    "damage_low": 12,
    "damage_high": 16,
    "health": 70,
    "speed": 6,
    "growth": 3,
    "aiValue": 1028,
    "cost": 600,
    "specials": "Death stare 10% chance/unit",
    "imageSrc": "./img/Fortress/Mighty Gorgons.PNG",
    "damage": "12-16",
    "archerDamage": 0,
    "type": "Tank"
  },
  {
    "name": "Wyverns",
    "townName": "Fortress",
    "level": "6",
    "attack": 14,
    "defense": 14,
    "damage_low": 14,
    "damage_high": 18,
    "health": 70,
    "speed": 7,
    "growth": 2,
    "aiValue": 1350,
    "cost": 800,
    "specials": "Flying",
    "imageSrc": "./img/Fortress/Wyverns.PNG",
    "damage": "14-18",
    "archerDamage": 0,
    "type": "Fast Tank"
  },
  {
    "name": "Wyvern Monarches",
    "townName": "Fortress",
    "level": "6+",
    "attack": 14,
    "defense": 14,
    "damage_low": 18,
    "damage_high": 22,
    "health": 70,
    "speed": 11,
    "growth": 2,
    "aiValue": 1518,
    "cost": 1100,
    "specials": "Flying, Poison",
    "imageSrc": "./img/Fortress/Wyvern Monarches.PNG",
    "damage": "18-22",
    "archerDamage": 0,
    "type": "Fast Tank"
  },
  {
    "name": "Hydras",
    "townName": "Fortress",
    "level": "7",
    "attack": 16,
    "defense": 18,
    "damage_low": 25,
    "damage_high": 45,
    "health": 175,
    "speed": 5,
    "growth": 1,
    "aiValue": 4120,
    "cost": 2200,
    "specials": "No enemy retaliation, Attack all adjacent enemies",
    "imageSrc": "./img/Fortress/Hydras.PNG",
    "damage": "25-45",
    "archerDamage": 0,
    "type": "Tank"
  },
  {
    "name": "Chaos Hydras",
    "townName": "Fortress",
    "level": "7+",
    "attack": 18,
    "defense": 20,
    "damage_low": 25,
    "damage_high": 45,
    "health": 250,
    "speed": 7,
    "growth": 1,
    "aiValue": 5931,
    "cost": 3500,
    "specials": "No enemy retaliation, Attack all adjacent enemies",
    "imageSrc": "./img/Fortress/Chaos Hydras.PNG",
    "damage": "25-45",
    "archerDamage": 0,
    "type": "Fast Tank"
  },
  {
    "name": "Imps",
    "townName": "Inferno",
    "level": "1",
    "attack": 2,
    "defense": 3,
    "damage_low": 1,
    "damage_high": 2,
    "health": 4,
    "speed": 5,
    "growth": 15,
    "aiValue": 50,
    "cost": 50,
    "specials": "",
    "imageSrc": "./img/Inferno/Imps.PNG",
    "damage": "1-2",
    "archerDamage": 0,
    "type": "Weak"
  },
  {
    "name": "Familiars",
    "townName": "Inferno",
    "level": "1+",
    "attack": 4,
    "defense": 4,
    "damage_low": 1,
    "damage_high": 2,
    "health": 4,
    "speed": 7,
    "growth": 15,
    "aiValue": 60,
    "cost": 60,
    "specials": "Magic channel",
    "imageSrc": "./img/Inferno/Familiars.PNG",
    "damage": "1-2",
    "archerDamage": 0,
    "type": "Fast"
  },
  {
    "name": "Gogs",
    "townName": "Inferno",
    "level": "2",
    "attack": 6,
    "defense": 4,
    "damage_low": 2,
    "damage_high": 4,
    "health": 13,
    "speed": 4,
    "growth": 8,
    "aiValue": 159,
    "cost": 125,
    "specials": "Ranged (12 shots)",
    "imageSrc": "./img/Inferno/Gogs.PNG",
    "damage": "2-4",
    "archerDamage": 12,
    "type": "Archer (12dmg)"
  },
  {
    "name": "Magogs",
    "townName": "Inferno",
    "level": "2+",
    "attack": 7,
    "defense": 4,
    "damage_low": 2,
    "damage_high": 4,
    "health": 13,
    "speed": 6,
    "growth": 8,
    "aiValue": 240,
    "cost": 175,
    "specials": "Ranged (24 shots), Fireball attack",
    "imageSrc": "./img/Inferno/Magogs.PNG",
    "damage": "2-4",
    "archerDamage": 24,
    "type": "Archer (24dmg)"
  },
  {
    "name": "Hell Hounds",
    "townName": "Inferno",
    "level": "3",
    "attack": 10,
    "defense": 6,
    "damage_low": 2,
    "damage_high": 7,
    "health": 25,
    "speed": 7,
    "growth": 5,
    "aiValue": 357,
    "cost": 200,
    "specials": "",
    "imageSrc": "./img/Inferno/Hell Hounds.PNG",
    "damage": "2-7",
    "archerDamage": 0,
    "type": "Fast"
  },
  {
    "name": "Cerberuses",
    "townName": "Inferno",
    "level": "3+",
    "attack": 10,
    "defense": 8,
    "damage_low": 2,
    "damage_high": 7,
    "health": 25,
    "speed": 8,
    "growth": 5,
    "aiValue": 392,
    "cost": 250,
    "specials": "No enemy retaliation, 3-headed attack",
    "imageSrc": "./img/Inferno/Cerberuses.PNG",
    "damage": "2-7",
    "archerDamage": 0,
    "type": "Fast"
  },
  {
    "name": "Demons",
    "townName": "Inferno",
    "level": "4",
    "attack": 10,
    "defense": 10,
    "damage_low": 7,
    "damage_high": 9,
    "health": 35,
    "speed": 5,
    "growth": 4,
    "aiValue": 445,
    "cost": 250,
    "specials": "",
    "imageSrc": "./img/Inferno/Demons.PNG",
    "damage": "7-9",
    "archerDamage": 0,
    "type": ""
  },
  {
    "name": "Horned Demons",
    "townName": "Inferno",
    "level": "4+",
    "attack": 10,
    "defense": 10,
    "damage_low": 7,
    "damage_high": 9,
    "health": 40,
    "speed": 6,
    "growth": 4,
    "aiValue": 480,
    "cost": 270,
    "specials": "",
    "imageSrc": "./img/Inferno/Horned Demons.PNG",
    "damage": "7-9",
    "archerDamage": 0,
    "type": ""
  },
  {
    "name": "Pit Fiends",
    "townName": "Inferno",
    "level": "5",
    "attack": 13,
    "defense": 13,
    "damage_low": 13,
    "damage_high": 17,
    "health": 45,
    "speed": 6,
    "growth": 3,
    "aiValue": 765,
    "cost": 500,
    "specials": "",
    "imageSrc": "./img/Inferno/Pit Fiends.PNG",
    "damage": "13-17",
    "archerDamage": 0,
    "type": ""
  },
  {
    "name": "Pit Lords",
    "townName": "Inferno",
    "level": "5+",
    "attack": 13,
    "defense": 13,
    "damage_low": 13,
    "damage_high": 17,
    "health": 45,
    "speed": 7,
    "growth": 3,
    "aiValue": 1224,
    "cost": 700,
    "specials": "Summon demons",
    "imageSrc": "./img/Inferno/Pit Lords.PNG",
    "damage": "13-17",
    "archerDamage": 0,
    "type": "Fast"
  },
  {
    "name": "Efreets",
    "townName": "Inferno",
    "level": "6",
    "attack": 16,
    "defense": 12,
    "damage_low": 16,
    "damage_high": 24,
    "health": 90,
    "speed": 9,
    "growth": 2,
    "aiValue": 1670,
    "cost": 900,
    "specials": "Flying, Fire immunity",
    "imageSrc": "./img/Inferno/Efreets.PNG",
    "damage": "16-24",
    "archerDamage": 0,
    "type": "Fast Tank"
  },
  {
    "name": "Efreet Sultans",
    "townName": "Inferno",
    "level": "6+",
    "attack": 16,
    "defense": 14,
    "damage_low": 16,
    "damage_high": 24,
    "health": 90,
    "speed": 13,
    "growth": 2,
    "aiValue": 2343,
    "cost": 1100,
    "specials": "Flying, Fire shield, Fire immunity, Hates Genies",
    "imageSrc": "./img/Inferno/Efreet Sultans.PNG",
    "damage": "16-24",
    "archerDamage": 0,
    "type": "Fast Tank"
  },
  {
    "name": "Devils",
    "townName": "Inferno",
    "level": "7",
    "attack": 19,
    "defense": 21,
    "damage_low": 30,
    "damage_high": 40,
    "health": 160,
    "speed": 11,
    "growth": 1,
    "aiValue": 5101,
    "cost": 2700,
    "specials": "Teleporting, No enemy retaliation, Luck -1, Hates Angels",
    "imageSrc": "./img/Inferno/Devils.PNG",
    "damage": "30-40",
    "archerDamage": 0,
    "type": "Fast Tank"
  },
  {
    "name": "Arch Devils",
    "townName": "Inferno",
    "level": "7+",
    "attack": 26,
    "defense": 28,
    "damage_low": 30,
    "damage_high": 40,
    "health": 200,
    "speed": 17,
    "growth": 1,
    "aiValue": 7115,
    "cost": 4500,
    "specials": "Teleporting, No enemy retaliation, Luck -2, Hates Angels",
    "imageSrc": "./img/Inferno/Arch Devils.PNG",
    "damage": "30-40",
    "archerDamage": 0,
    "type": "Fast Tank"
  },
  {
    "name": "Skeletons",
    "townName": "Necropolis",
    "level": "1",
    "attack": 5,
    "defense": 4,
    "damage_low": 1,
    "damage_high": 3,
    "health": 6,
    "speed": 4,
    "growth": 12,
    "aiValue": 60,
    "cost": 60,
    "specials": "Undead",
    "imageSrc": "./img/Necropolis/Skeletons.PNG",
    "damage": "1-3",
    "archerDamage": 0,
    "type": "Weak"
  },
  {
    "name": "Skeleton Warriors",
    "townName": "Necropolis",
    "level": "1+",
    "attack": 6,
    "defense": 6,
    "damage_low": 1,
    "damage_high": 3,
    "health": 6,
    "speed": 5,
    "growth": 12,
    "aiValue": 85,
    "cost": 70,
    "specials": "Undead",
    "imageSrc": "./img/Necropolis/Skeleton Warriors.PNG",
    "damage": "1-3",
    "archerDamage": 0,
    "type": "Weak"
  },
  {
    "name": "Walking Deads",
    "townName": "Necropolis",
    "level": "2",
    "attack": 5,
    "defense": 5,
    "damage_low": 2,
    "damage_high": 3,
    "health": 15,
    "speed": 3,
    "growth": 8,
    "aiValue": 98,
    "cost": 100,
    "specials": "Undead",
    "imageSrc": "./img/Necropolis/Walking Deads.PNG",
    "damage": "2-3",
    "archerDamage": 0,
    "type": ""
  },
  {
    "name": "Zombies",
    "townName": "Necropolis",
    "level": "2+",
    "attack": 5,
    "defense": 5,
    "damage_low": 2,
    "damage_high": 3,
    "health": 20,
    "speed": 4,
    "growth": 8,
    "aiValue": 128,
    "cost": 125,
    "specials": "Undead, Disease",
    "imageSrc": "./img/Necropolis/Zombies.PNG",
    "damage": "2-3",
    "archerDamage": 0,
    "type": ""
  },
  {
    "name": "Wights",
    "townName": "Necropolis",
    "level": "3",
    "attack": 7,
    "defense": 7,
    "damage_low": 3,
    "damage_high": 5,
    "health": 18,
    "speed": 5,
    "growth": 7,
    "aiValue": 252,
    "cost": 200,
    "specials": "Undead, Flying, Regeneration",
    "imageSrc": "./img/Necropolis/Wights.PNG",
    "damage": "3-5",
    "archerDamage": 0,
    "type": ""
  },
  {
    "name": "Wraiths",
    "townName": "Necropolis",
    "level": "3+",
    "attack": 7,
    "defense": 7,
    "damage_low": 3,
    "damage_high": 5,
    "health": 18,
    "speed": 7,
    "growth": 7,
    "aiValue": 315,
    "cost": 230,
    "specials": "Undead, Flying, Regeneration, Mana drain",
    "imageSrc": "./img/Necropolis/Wraiths.PNG",
    "damage": "3-5",
    "archerDamage": 0,
    "type": "Fast"
  },
  {
    "name": "Vampires",
    "townName": "Necropolis",
    "level": "4",
    "attack": 10,
    "defense": 9,
    "damage_low": 5,
    "damage_high": 8,
    "health": 30,
    "speed": 6,
    "growth": 4,
    "aiValue": 555,
    "cost": 360,
    "specials": "Undead, Flying, No retaliation",
    "imageSrc": "./img/Necropolis/Vampires.PNG",
    "damage": "5-8",
    "archerDamage": 0,
    "type": ""
  },
  {
    "name": "Vampire Lords",
    "townName": "Necropolis",
    "level": "4+",
    "attack": 10,
    "defense": 10,
    "damage_low": 5,
    "damage_high": 8,
    "health": 40,
    "speed": 9,
    "growth": 4,
    "aiValue": 783,
    "cost": 500,
    "specials": "Undead, Flying, No retaliation, Life drain",
    "imageSrc": "./img/Necropolis/Vampire Lords.PNG",
    "damage": "5-8",
    "archerDamage": 0,
    "type": "Fast"
  },
  {
    "name": "Liches",
    "townName": "Necropolis",
    "level": "5",
    "attack": 13,
    "defense": 10,
    "damage_low": 11,
    "damage_high": 13,
    "health": 30,
    "speed": 6,
    "growth": 3,
    "aiValue": 848,
    "cost": 550,
    "specials": "Ranged (12 shots), Undead, Death cloud",
    "imageSrc": "./img/Necropolis/Liches.PNG",
    "damage": "11-13",
    "archerDamage": 12,
    "type": "Archer (12dmg)"
  },
  {
    "name": "Power Liches",
    "townName": "Necropolis",
    "level": "5+",
    "attack": 13,
    "defense": 10,
    "damage_low": 11,
    "damage_high": 15,
    "health": 40,
    "speed": 7,
    "growth": 3,
    "aiValue": 1079,
    "cost": 600,
    "specials": "Ranged (24 shots), Undead, Death cloud",
    "imageSrc": "./img/Necropolis/Power Liches.PNG",
    "damage": "11-15",
    "archerDamage": 24,
    "type": "Archer (24dmg) Fast"
  },
  {
    "name": "Black Knights",
    "townName": "Necropolis",
    "level": "6",
    "attack": 16,
    "defense": 16,
    "damage_low": 15,
    "damage_high": 30,
    "health": 120,
    "speed": 7,
    "growth": 2,
    "aiValue": 2087,
    "cost": 1200,
    "specials": "Undead, Curse",
    "imageSrc": "./img/Necropolis/Black Knights.PNG",
    "damage": "15-30",
    "archerDamage": 0,
    "type": "Fast Tank"
  },
  {
    "name": "Dread Knights",
    "townName": "Necropolis",
    "level": "6+",
    "attack": 18,
    "defense": 18,
    "damage_low": 15,
    "damage_high": 30,
    "health": 120,
    "speed": 9,
    "growth": 2,
    "aiValue": 2382,
    "cost": 1500,
    "specials": "Undead, Curse, Death blow",
    "imageSrc": "./img/Necropolis/Dread Knights.PNG",
    "damage": "15-30",
    "archerDamage": 0,
    "type": "Fast Tank"
  },
  {
    "name": "Bone Dragons",
    "townName": "Necropolis",
    "level": "7",
    "attack": 17,
    "defense": 15,
    "damage_low": 25,
    "damage_high": 50,
    "health": 150,
    "speed": 9,
    "growth": 1,
    "aiValue": 3388,
    "cost": 1800,
    "specials": "Dragon, Undead, Flying, Morale -1",
    "imageSrc": "./img/Necropolis/Bone Dragons.PNG",
    "damage": "25-50",
    "archerDamage": 0,
    "type": "Fast Tank"
  },
  {
    "name": "Ghost Dragons",
    "townName": "Necropolis",
    "level": "7+",
    "attack": 19,
    "defense": 17,
    "damage_low": 25,
    "damage_high": 50,
    "health": 200,
    "speed": 14,
    "growth": 1,
    "aiValue": 4696,
    "cost": 3000,
    "specials": "Dragon, Undead, Flying, Morale -1, Aging",
    "imageSrc": "./img/Necropolis/Ghost Dragons.PNG",
    "damage": "25-50",
    "archerDamage": 0,
    "type": "Fast Tank"
  },
  {
    "name": "Peasants",
    "townName": "Neutral",
    "level": "1",
    "attack": 1,
    "defense": 1,
    "damage_low": 1,
    "damage_high": 1,
    "health": 1,
    "speed": 3,
    "growth": 25,
    "aiValue": 15,
    "cost": 10,
    "specials": "",
    "imageSrc": "./img/Neutral/Peasants.PNG",
    "damage": "1-1",
    "archerDamage": 0,
    "type": "Weak"
  },
  {
    "name": "Halflings",
    "townName": "Neutral",
    "level": "1",
    "attack": 4,
    "defense": 2,
    "damage_low": 1,
    "damage_high": 3,
    "health": 4,
    "speed": 5,
    "growth": 15,
    "aiValue": 75,
    "cost": 40,
    "specials": "Ranged (24 shots), Positive Luck",
    "imageSrc": "./img/Neutral/Halflings.PNG",
    "damage": "1-3",
    "archerDamage": 24,
    "type": "Archer (24dmg)"
  },
  {
    "name": "Boars",
    "townName": "Neutral",
    "level": "2",
    "attack": 6,
    "defense": 5,
    "damage_low": 2,
    "damage_high": 3,
    "health": 15,
    "speed": 6,
    "growth": 8,
    "aiValue": 145,
    "cost": 150,
    "specials": "",
    "imageSrc": "./img/Neutral/Boars.PNG",
    "damage": "2-3",
    "archerDamage": 0,
    "type": ""
  },
  {
    "name": "Rogues",
    "townName": "Neutral",
    "level": "2",
    "attack": 8,
    "defense": 3,
    "damage_low": 2,
    "damage_high": 4,
    "health": 10,
    "speed": 6,
    "growth": 8,
    "aiValue": 135,
    "cost": 100,
    "specials": "Spying",
    "imageSrc": "./img/Neutral/Rogues.PNG",
    "damage": "2-4",
    "archerDamage": 0,
    "type": ""
  },
  {
    "name": "Leprechauns",
    "townName": "Neutral",
    "level": "2",
    "attack": 8,
    "defense": 5,
    "damage_low": 3,
    "damage_high": 5,
    "health": 15,
    "speed": 5,
    "growth": 9,
    "aiValue": 208,
    "cost": 100,
    "specials": "Doubles friendly unit Luck chance, Casts Fortune",
    "imageSrc": "./img/Neutral/Leprechauns.PNG",
    "damage": "3-5",
    "archerDamage": 0,
    "type": ""
  },
  {
    "name": "Mummys",
    "townName": "Neutral",
    "level": "3",
    "attack": 7,
    "defense": 7,
    "damage_low": 3,
    "damage_high": 5,
    "health": 30,
    "speed": 5,
    "growth": 7,
    "aiValue": 270,
    "cost": 300,
    "specials": "Undead, Curse",
    "imageSrc": "./img/Neutral/Mummys.PNG",
    "damage": "3-5",
    "archerDamage": 0,
    "type": ""
  },
  {
    "name": "Nomads",
    "townName": "Neutral",
    "level": "3",
    "attack": 9,
    "defense": 8,
    "damage_low": 2,
    "damage_high": 6,
    "health": 30,
    "speed": 7,
    "growth": 7,
    "aiValue": 345,
    "cost": 200,
    "specials": "Sandwalker",
    "imageSrc": "./img/Neutral/Nomads.PNG",
    "damage": "2-6",
    "archerDamage": 0,
    "type": "Fast"
  },
  {
    "name": "Sharpshooters",
    "townName": "Neutral",
    "level": "4",
    "attack": 12,
    "defense": 10,
    "damage_low": 8,
    "damage_high": 10,
    "health": 15,
    "speed": 9,
    "growth": 4,
    "aiValue": 585,
    "cost": 400,
    "specials": "Ranged (32 shots), No range and obstacle penalty",
    "imageSrc": "./img/Neutral/Sharpshooters.PNG",
    "damage": "8-10",
    "archerDamage": 32,
    "type": "Archer (32dmg) Fast"
  },
  {
    "name": "Satyrs",
    "townName": "Neutral",
    "level": "4",
    "attack": 10,
    "defense": 11,
    "damage_low": 6,
    "damage_high": 10,
    "health": 35,
    "speed": 7,
    "growth": 4,
    "aiValue": 518,
    "cost": 300,
    "specials": "Casts Mirth",
    "imageSrc": "./img/Neutral/Satyrs.PNG",
    "damage": "6-10",
    "archerDamage": 0,
    "type": "Fast"
  },
  {
    "name": "Steel Golems",
    "townName": "Neutral",
    "level": "4",
    "attack": 10,
    "defense": 11,
    "damage_low": 6,
    "damage_high": 8,
    "health": 45,
    "speed": 6,
    "growth": 4,
    "aiValue": 597,
    "cost": 400,
    "specials": "Unliving, Spell Damage Resistance +80%",
    "imageSrc": "./img/Neutral/Steel Golems.PNG",
    "damage": "6-8",
    "archerDamage": 0,
    "type": ""
  },
  {
    "name": "Trolls",
    "townName": "Neutral",
    "level": "5",
    "attack": 14,
    "defense": 7,
    "damage_low": 10,
    "damage_high": 15,
    "health": 40,
    "speed": 7,
    "growth": 3,
    "aiValue": 1024,
    "cost": 500,
    "specials": "Regeneration",
    "imageSrc": "./img/Neutral/Trolls.PNG",
    "damage": "10-15",
    "archerDamage": 0,
    "type": "Fast"
  },
  {
    "name": "Gold Golems",
    "townName": "Neutral",
    "level": "5",
    "attack": 11,
    "defense": 12,
    "damage_low": 8,
    "damage_high": 10,
    "health": 50,
    "speed": 5,
    "growth": 3,
    "aiValue": 600,
    "cost": 500,
    "specials": "Unliving, Spell Damage Resistance +85%",
    "imageSrc": "./img/Neutral/Gold Golems.PNG",
    "damage": "8-10",
    "archerDamage": 0,
    "type": ""
  },
  {
    "name": "Fangarms",
    "townName": "Neutral",
    "level": "5",
    "attack": 12,
    "defense": 12,
    "damage_low": 8,
    "damage_high": 12,
    "health": 50,
    "speed": 6,
    "growth": 3,
    "aiValue": 929,
    "cost": 600,
    "specials": "Flying, Mind spell immunity, Unlimited retaliations, Casts Hypnotize on attacked stack",
    "imageSrc": "./img/Neutral/Fangarms.PNG",
    "damage": "8-12",
    "archerDamage": 0,
    "type": ""
  },
  {
    "name": "Diamond Golems",
    "townName": "Neutral",
    "level": "6",
    "attack": 13,
    "defense": 12,
    "damage_low": 10,
    "damage_high": 14,
    "health": 60,
    "speed": 5,
    "growth": 2,
    "aiValue": 775,
    "cost": 750,
    "specials": "Unliving, Spell Damage Resistance +95%",
    "imageSrc": "./img/Neutral/Diamond Golems.PNG",
    "damage": "10-14",
    "archerDamage": 0,
    "type": "Tank"
  },
  {
    "name": "Enchanters",
    "townName": "Neutral",
    "level": "6",
    "attack": 17,
    "defense": 12,
    "damage_low": 14,
    "damage_high": 14,
    "health": 30,
    "speed": 9,
    "growth": 2,
    "aiValue": 1210,
    "cost": 750,
    "specials": "Ranged (32 shots), No melee and obstacle penalty, Spellcaster",
    "imageSrc": "./img/Neutral/Enchanters.PNG",
    "damage": "14-14",
    "archerDamage": 32,
    "type": "Archer (32dmg) Fast"
  },
  {
    "name": "Faerie Dragons",
    "townName": "Neutral",
    "level": "7",
    "attack": 20,
    "defense": 20,
    "damage_low": 20,
    "damage_high": 30,
    "health": 500,
    "speed": 15,
    "growth": 1,
    "aiValue": 30501,
    "cost": 10000,
    "specials": "Dragon, Flying, Spellcaster, Magic Mirror",
    "imageSrc": "./img/Neutral/Faerie Dragons.PNG",
    "damage": "20-30",
    "archerDamage": 0,
    "type": "Fast Tank"
  },
  {
    "name": "Rust Dragons",
    "townName": "Neutral",
    "level": "7",
    "attack": 30,
    "defense": 30,
    "damage_low": 50,
    "damage_high": 50,
    "health": 750,
    "speed": 17,
    "growth": 1,
    "aiValue": 26433,
    "cost": 15000,
    "specials": "Dragon, Flying, Breath, Acid breath",
    "imageSrc": "./img/Neutral/Rust Dragons.PNG",
    "damage": "50-50",
    "archerDamage": 0,
    "type": "Fast Tank"
  },
  {
    "name": "Crystal Dragons",
    "townName": "Neutral",
    "level": "7",
    "attack": 40,
    "defense": 40,
    "damage_low": 60,
    "damage_high": 75,
    "health": 800,
    "speed": 16,
    "growth": 1,
    "aiValue": 39338,
    "cost": 20000,
    "specials": "Dragon, Crystal generation, Magic resistance +20%",
    "imageSrc": "./img/Neutral/Crystal Dragons.PNG",
    "damage": "60-75",
    "archerDamage": 0,
    "type": "Fast Tank"
  },
  {
    "name": "Azure Dragons",
    "townName": "Neutral",
    "level": "7",
    "attack": 50,
    "defense": 50,
    "damage_low": 70,
    "damage_high": 80,
    "health": 1000,
    "speed": 19,
    "growth": 1,
    "aiValue": 78845,
    "cost": 30000,
    "specials": "Dragon, Flying, Breath, Fear, Resist lvl 1\u20133 spells, Resist Fear",
    "imageSrc": "./img/Neutral/Azure Dragons.PNG",
    "damage": "70-80",
    "archerDamage": 0,
    "type": "Fast Tank"
  },
  {
    "name": "Centaurs",
    "townName": "Rampart",
    "level": "1",
    "attack": 5,
    "defense": 3,
    "damage_low": 2,
    "damage_high": 3,
    "health": 8,
    "speed": 6,
    "growth": 14,
    "aiValue": 100,
    "cost": 70,
    "specials": "",
    "imageSrc": "./img/Rampart/Centaurs.PNG",
    "damage": "2-3",
    "archerDamage": 0,
    "type": "Weak"
  },
  {
    "name": "Centaur Captains",
    "townName": "Rampart",
    "level": "1+",
    "attack": 6,
    "defense": 3,
    "damage_low": 2,
    "damage_high": 3,
    "health": 10,
    "speed": 8,
    "growth": 14,
    "aiValue": 138,
    "cost": 90,
    "specials": "",
    "imageSrc": "./img/Rampart/Centaur Captains.PNG",
    "damage": "2-3",
    "archerDamage": 0,
    "type": "Fast"
  },
  {
    "name": "Dwarves",
    "townName": "Rampart",
    "level": "2",
    "attack": 6,
    "defense": 7,
    "damage_low": 2,
    "damage_high": 4,
    "health": 20,
    "speed": 3,
    "growth": 8,
    "aiValue": 138,
    "cost": 120,
    "specials": "Resistance +20%",
    "imageSrc": "./img/Rampart/Dwarves.PNG",
    "damage": "2-4",
    "archerDamage": 0,
    "type": ""
  },
  {
    "name": "Battle Dwarves",
    "townName": "Rampart",
    "level": "2+",
    "attack": 7,
    "defense": 7,
    "damage_low": 2,
    "damage_high": 4,
    "health": 20,
    "speed": 5,
    "growth": 8,
    "aiValue": 209,
    "cost": 150,
    "specials": "Resistance +40%",
    "imageSrc": "./img/Rampart/Battle Dwarves.PNG",
    "damage": "2-4",
    "archerDamage": 0,
    "type": ""
  },
  {
    "name": "Wood Elves",
    "townName": "Rampart",
    "level": "3",
    "attack": 9,
    "defense": 5,
    "damage_low": 3,
    "damage_high": 5,
    "health": 15,
    "speed": 6,
    "growth": 7,
    "aiValue": 234,
    "cost": 200,
    "specials": "Ranged (24 shots)",
    "imageSrc": "./img/Rampart/Wood Elves.PNG",
    "damage": "3-5",
    "archerDamage": 24,
    "type": "Archer (24dmg)"
  },
  {
    "name": "Grand Elves",
    "townName": "Rampart",
    "level": "3+",
    "attack": 9,
    "defense": 5,
    "damage_low": 3,
    "damage_high": 5,
    "health": 15,
    "speed": 7,
    "growth": 7,
    "aiValue": 331,
    "cost": 225,
    "specials": "Ranged (24 shots), Double attack",
    "imageSrc": "./img/Rampart/Grand Elves.PNG",
    "damage": "3-5",
    "archerDamage": 24,
    "type": "Archer (24dmg) Fast"
  },
  {
    "name": "Pegasuses",
    "townName": "Rampart",
    "level": "4",
    "attack": 9,
    "defense": 8,
    "damage_low": 5,
    "damage_high": 9,
    "health": 30,
    "speed": 8,
    "growth": 5,
    "aiValue": 518,
    "cost": 250,
    "specials": "Flying, Magic damper",
    "imageSrc": "./img/Rampart/Pegasuses.PNG",
    "damage": "5-9",
    "archerDamage": 0,
    "type": "Fast"
  },
  {
    "name": "Silver Pegasuses",
    "townName": "Rampart",
    "level": "4+",
    "attack": 9,
    "defense": 10,
    "damage_low": 5,
    "damage_high": 9,
    "health": 30,
    "speed": 12,
    "growth": 5,
    "aiValue": 532,
    "cost": 275,
    "specials": "Flying, Magic damper",
    "imageSrc": "./img/Rampart/Silver Pegasuses.PNG",
    "damage": "5-9",
    "archerDamage": 0,
    "type": "Fast"
  },
  {
    "name": "Dendroid Guards",
    "townName": "Rampart",
    "level": "5",
    "attack": 9,
    "defense": 12,
    "damage_low": 10,
    "damage_high": 14,
    "health": 55,
    "speed": 3,
    "growth": 3,
    "aiValue": 517,
    "cost": 350,
    "specials": "Binding",
    "imageSrc": "./img/Rampart/Dendroid Guards.PNG",
    "damage": "10-14",
    "archerDamage": 0,
    "type": "Tank"
  },
  {
    "name": "Dendroid Soldiers",
    "townName": "Rampart",
    "level": "5+",
    "attack": 9,
    "defense": 12,
    "damage_low": 10,
    "damage_high": 14,
    "health": 65,
    "speed": 4,
    "growth": 3,
    "aiValue": 803,
    "cost": 425,
    "specials": "Binding",
    "imageSrc": "./img/Rampart/Dendroid Soldiers.PNG",
    "damage": "10-14",
    "archerDamage": 0,
    "type": "Tank"
  },
  {
    "name": "Unicorns",
    "townName": "Rampart",
    "level": "6",
    "attack": 15,
    "defense": 14,
    "damage_low": 18,
    "damage_high": 22,
    "health": 90,
    "speed": 7,
    "growth": 2,
    "aiValue": 1806,
    "cost": 850,
    "specials": "Blind, Aura of Resistance +20%",
    "imageSrc": "./img/Rampart/Unicorns.PNG",
    "damage": "18-22",
    "archerDamage": 0,
    "type": "Fast Tank"
  },
  {
    "name": "War Unicorns",
    "townName": "Rampart",
    "level": "6+",
    "attack": 15,
    "defense": 14,
    "damage_low": 18,
    "damage_high": 22,
    "health": 110,
    "speed": 9,
    "growth": 2,
    "aiValue": 2030,
    "cost": 950,
    "specials": "Blind, Aura of Resistance +20%",
    "imageSrc": "./img/Rampart/War Unicorns.PNG",
    "damage": "18-22",
    "archerDamage": 0,
    "type": "Fast Tank"
  },
  {
    "name": "Green Dragons",
    "townName": "Rampart",
    "level": "7",
    "attack": 18,
    "defense": 18,
    "damage_low": 40,
    "damage_high": 50,
    "health": 180,
    "speed": 10,
    "growth": 1,
    "aiValue": 4872,
    "cost": 2400,
    "specials": "Dragon, Flying, Breath attack, 1-3 lvl spells immunity",
    "imageSrc": "./img/Rampart/Green Dragons.PNG",
    "damage": "40-50",
    "archerDamage": 0,
    "type": "Fast Tank"
  },
  {
    "name": "Gold Dragons",
    "townName": "Rampart",
    "level": "7+",
    "attack": 27,
    "defense": 27,
    "damage_low": 40,
    "damage_high": 50,
    "health": 250,
    "speed": 16,
    "growth": 1,
    "aiValue": 8613,
    "cost": 4000,
    "specials": "Dragon, Flying, Breath attack, 1-4 lvl spells immunity",
    "imageSrc": "./img/Rampart/Gold Dragons.PNG",
    "damage": "40-50",
    "archerDamage": 0,
    "type": "Fast Tank"
  },
  {
    "name": "Goblins",
    "townName": "Stronghold",
    "level": "1",
    "attack": 4,
    "defense": 2,
    "damage_low": 1,
    "damage_high": 2,
    "health": 5,
    "speed": 5,
    "growth": 15,
    "aiValue": 60,
    "cost": 40,
    "specials": "",
    "imageSrc": "./img/Stronghold/Goblins.PNG",
    "damage": "1-2",
    "archerDamage": 0,
    "type": "Weak"
  },
  {
    "name": "Hobgoblins",
    "townName": "Stronghold",
    "level": "1+",
    "attack": 5,
    "defense": 3,
    "damage_low": 1,
    "damage_high": 2,
    "health": 5,
    "speed": 7,
    "growth": 15,
    "aiValue": 78,
    "cost": 50,
    "specials": "",
    "imageSrc": "./img/Stronghold/Hobgoblins.PNG",
    "damage": "1-2",
    "archerDamage": 0,
    "type": "Fast"
  },
  {
    "name": "Wolf Riders",
    "townName": "Stronghold",
    "level": "2",
    "attack": 7,
    "defense": 5,
    "damage_low": 2,
    "damage_high": 4,
    "health": 10,
    "speed": 6,
    "growth": 9,
    "aiValue": 130,
    "cost": 100,
    "specials": "",
    "imageSrc": "./img/Stronghold/Wolf Riders.PNG",
    "damage": "2-4",
    "archerDamage": 0,
    "type": ""
  },
  {
    "name": "Wolf Raiders",
    "townName": "Stronghold",
    "level": "2+",
    "attack": 8,
    "defense": 5,
    "damage_low": 3,
    "damage_high": 4,
    "health": 10,
    "speed": 8,
    "growth": 9,
    "aiValue": 203,
    "cost": 140,
    "specials": "Double attack",
    "imageSrc": "./img/Stronghold/Wolf Raiders.PNG",
    "damage": "3-4",
    "archerDamage": 0,
    "type": "Fast"
  },
  {
    "name": "Orcs",
    "townName": "Stronghold",
    "level": "3",
    "attack": 8,
    "defense": 4,
    "damage_low": 2,
    "damage_high": 5,
    "health": 15,
    "speed": 4,
    "growth": 7,
    "aiValue": 192,
    "cost": 150,
    "specials": "Ranged (12 shots)",
    "imageSrc": "./img/Stronghold/Orcs.PNG",
    "damage": "2-5",
    "archerDamage": 12,
    "type": "Archer (12dmg)"
  },
  {
    "name": "Orc Chieftains",
    "townName": "Stronghold",
    "level": "3+",
    "attack": 8,
    "defense": 4,
    "damage_low": 2,
    "damage_high": 5,
    "health": 20,
    "speed": 5,
    "growth": 7,
    "aiValue": 240,
    "cost": 165,
    "specials": "Ranged (24 shots)",
    "imageSrc": "./img/Stronghold/Orc Chieftains.PNG",
    "damage": "2-5",
    "archerDamage": 24,
    "type": "Archer (24dmg)"
  },
  {
    "name": "Ogres",
    "townName": "Stronghold",
    "level": "4",
    "attack": 13,
    "defense": 7,
    "damage_low": 6,
    "damage_high": 12,
    "health": 40,
    "speed": 4,
    "growth": 4,
    "aiValue": 416,
    "cost": 300,
    "specials": "",
    "imageSrc": "./img/Stronghold/Ogres.PNG",
    "damage": "6-12",
    "archerDamage": 0,
    "type": ""
  },
  {
    "name": "Ogre Mages",
    "townName": "Stronghold",
    "level": "4+",
    "attack": 13,
    "defense": 7,
    "damage_low": 6,
    "damage_high": 12,
    "health": 60,
    "speed": 5,
    "growth": 4,
    "aiValue": 672,
    "cost": 400,
    "specials": "Cast Bloodlust x3",
    "imageSrc": "./img/Stronghold/Ogre Mages.PNG",
    "damage": "6-12",
    "archerDamage": 0,
    "type": "Tank"
  },
  {
    "name": "Rocs",
    "townName": "Stronghold",
    "level": "5",
    "attack": 13,
    "defense": 11,
    "damage_low": 11,
    "damage_high": 15,
    "health": 60,
    "speed": 7,
    "growth": 3,
    "aiValue": 1027,
    "cost": 600,
    "specials": "Flying",
    "imageSrc": "./img/Stronghold/Rocs.PNG",
    "damage": "11-15",
    "archerDamage": 0,
    "type": "Fast Tank"
  },
  {
    "name": "Thunderbirds",
    "townName": "Stronghold",
    "level": "5+",
    "attack": 13,
    "defense": 11,
    "damage_low": 11,
    "damage_high": 15,
    "health": 60,
    "speed": 11,
    "growth": 3,
    "aiValue": 1106,
    "cost": 700,
    "specials": "Flying, Lightning strike",
    "imageSrc": "./img/Stronghold/Thunderbirds.PNG",
    "damage": "11-15",
    "archerDamage": 0,
    "type": "Fast Tank"
  },
  {
    "name": "Cyclopss",
    "townName": "Stronghold",
    "level": "6",
    "attack": 15,
    "defense": 12,
    "damage_low": 16,
    "damage_high": 20,
    "health": 70,
    "speed": 6,
    "growth": 2,
    "aiValue": 1266,
    "cost": 750,
    "specials": "Ranged (16 shots), Can attack siege walls",
    "imageSrc": "./img/Stronghold/Cyclopss.PNG",
    "damage": "16-20",
    "archerDamage": 16,
    "type": "Archer (16dmg) Tank"
  },
  {
    "name": "Cyclops Kings",
    "townName": "Stronghold",
    "level": "6+",
    "attack": 17,
    "defense": 13,
    "damage_low": 16,
    "damage_high": 20,
    "health": 70,
    "speed": 8,
    "growth": 2,
    "aiValue": 1443,
    "cost": 1100,
    "specials": "Ranged (24 shots), Can attack siege walls",
    "imageSrc": "./img/Stronghold/Cyclops Kings.PNG",
    "damage": "16-20",
    "archerDamage": 24,
    "type": "Archer (24dmg) Fast Tank"
  },
  {
    "name": "Behemoths",
    "townName": "Stronghold",
    "level": "7",
    "attack": 17,
    "defense": 17,
    "damage_low": 30,
    "damage_high": 50,
    "health": 160,
    "speed": 6,
    "growth": 1,
    "aiValue": 3162,
    "cost": 1500,
    "specials": "Defense -40% to enemy target",
    "imageSrc": "./img/Stronghold/Behemoths.PNG",
    "damage": "30-50",
    "archerDamage": 0,
    "type": "Tank"
  },
  {
    "name": "Ancient Behemoths",
    "townName": "Stronghold",
    "level": "7+",
    "attack": 19,
    "defense": 19,
    "damage_low": 30,
    "damage_high": 50,
    "health": 300,
    "speed": 9,
    "growth": 1,
    "aiValue": 6168,
    "cost": 3000,
    "specials": "Defense -80% to enemy target",
    "imageSrc": "./img/Stronghold/Ancient Behemoths.PNG",
    "damage": "30-50",
    "archerDamage": 0,
    "type": "Fast Tank"
  },
  {
    "name": "Gremlins",
    "townName": "Tower",
    "level": "1",
    "attack": 3,
    "defense": 3,
    "damage_low": 1,
    "damage_high": 2,
    "health": 4,
    "speed": 4,
    "growth": 16,
    "aiValue": 44,
    "cost": 30,
    "specials": "",
    "imageSrc": "./img/Tower/Gremlins.PNG",
    "damage": "1-2",
    "archerDamage": 0,
    "type": "Weak"
  },
  {
    "name": "Master Gremlins",
    "townName": "Tower",
    "level": "1+",
    "attack": 4,
    "defense": 4,
    "damage_low": 1,
    "damage_high": 2,
    "health": 4,
    "speed": 5,
    "growth": 16,
    "aiValue": 66,
    "cost": 40,
    "specials": "Ranged (8 shots)",
    "imageSrc": "./img/Tower/Master Gremlins.PNG",
    "damage": "1-2",
    "archerDamage": 8,
    "type": "Archer (8dmg)"
  },
  {
    "name": "Stone Gargoyles",
    "townName": "Tower",
    "level": "2",
    "attack": 6,
    "defense": 6,
    "damage_low": 2,
    "damage_high": 3,
    "health": 16,
    "speed": 6,
    "growth": 9,
    "aiValue": 165,
    "cost": 130,
    "specials": "Unliving, Flying",
    "imageSrc": "./img/Tower/Stone Gargoyles.PNG",
    "damage": "2-3",
    "archerDamage": 0,
    "type": ""
  },
  {
    "name": "Obsidian Gargoyles",
    "townName": "Tower",
    "level": "2+",
    "attack": 7,
    "defense": 7,
    "damage_low": 2,
    "damage_high": 3,
    "health": 16,
    "speed": 9,
    "growth": 9,
    "aiValue": 201,
    "cost": 160,
    "specials": "Unliving, Flying",
    "imageSrc": "./img/Tower/Obsidian Gargoyles.PNG",
    "damage": "2-3",
    "archerDamage": 0,
    "type": "Fast"
  },
  {
    "name": "Stone Golems",
    "townName": "Tower",
    "level": "3",
    "attack": 7,
    "defense": 10,
    "damage_low": 4,
    "damage_high": 5,
    "health": 30,
    "speed": 3,
    "growth": 6,
    "aiValue": 250,
    "cost": 150,
    "specials": "Unliving, Spell Damage Resistance +50%",
    "imageSrc": "./img/Tower/Stone Golems.PNG",
    "damage": "4-5",
    "archerDamage": 0,
    "type": ""
  },
  {
    "name": "Iron Golems",
    "townName": "Tower",
    "level": "3+",
    "attack": 9,
    "defense": 10,
    "damage_low": 4,
    "damage_high": 5,
    "health": 35,
    "speed": 5,
    "growth": 6,
    "aiValue": 412,
    "cost": 200,
    "specials": "Unliving, Spell Damage Resistance +75%",
    "imageSrc": "./img/Tower/Iron Golems.PNG",
    "damage": "4-5",
    "archerDamage": 0,
    "type": ""
  },
  {
    "name": "Mages",
    "townName": "Tower",
    "level": "4",
    "attack": 11,
    "defense": 8,
    "damage_low": 7,
    "damage_high": 9,
    "health": 25,
    "speed": 5,
    "growth": 4,
    "aiValue": 570,
    "cost": 350,
    "specials": "Ranged (24 shots), No melee penalty, Spells cost -2 sp",
    "imageSrc": "./img/Tower/Mages.PNG",
    "damage": "7-9",
    "archerDamage": 24,
    "type": "Archer (24dmg)"
  },
  {
    "name": "Arch Mages",
    "townName": "Tower",
    "level": "4+",
    "attack": 12,
    "defense": 9,
    "damage_low": 7,
    "damage_high": 9,
    "health": 30,
    "speed": 7,
    "growth": 4,
    "aiValue": 680,
    "cost": 450,
    "specials": "Ranged (24 shots), No melee penalty, No obstacle penalty, Spells cost -2 sp",
    "imageSrc": "./img/Tower/Arch Mages.PNG",
    "damage": "7-9",
    "archerDamage": 24,
    "type": "Archer (24dmg) Fast"
  },
  {
    "name": "Genies",
    "townName": "Tower",
    "level": "5",
    "attack": 12,
    "defense": 12,
    "damage_low": 13,
    "damage_high": 16,
    "health": 40,
    "speed": 7,
    "growth": 3,
    "aiValue": 884,
    "cost": 550,
    "specials": "Flying, Hates Efreets",
    "imageSrc": "./img/Tower/Genies.PNG",
    "damage": "13-16",
    "archerDamage": 0,
    "type": "Fast"
  },
  {
    "name": "Master Genies",
    "townName": "Tower",
    "level": "5+",
    "attack": 12,
    "defense": 12,
    "damage_low": 13,
    "damage_high": 16,
    "health": 40,
    "speed": 11,
    "growth": 3,
    "aiValue": 942,
    "cost": 600,
    "specials": "Flying, Spellcaster, Hates Efreets",
    "imageSrc": "./img/Tower/Master Genies.PNG",
    "damage": "13-16",
    "archerDamage": 0,
    "type": "Fast"
  },
  {
    "name": "Nagas",
    "townName": "Tower",
    "level": "6",
    "attack": 16,
    "defense": 13,
    "damage_low": 20,
    "damage_high": 20,
    "health": 110,
    "speed": 5,
    "growth": 2,
    "aiValue": 2016,
    "cost": 1100,
    "specials": "No enemy retaliation",
    "imageSrc": "./img/Tower/Nagas.PNG",
    "damage": "20-20",
    "archerDamage": 0,
    "type": "Tank"
  },
  {
    "name": "Naga Queens",
    "townName": "Tower",
    "level": "6+",
    "attack": 16,
    "defense": 13,
    "damage_low": 30,
    "damage_high": 30,
    "health": 110,
    "speed": 7,
    "growth": 2,
    "aiValue": 2840,
    "cost": 1600,
    "specials": "No enemy retaliation",
    "imageSrc": "./img/Tower/Naga Queens.PNG",
    "damage": "30-30",
    "archerDamage": 0,
    "type": "Fast Tank"
  },
  {
    "name": "Giants",
    "townName": "Tower",
    "level": "7",
    "attack": 19,
    "defense": 16,
    "damage_low": 40,
    "damage_high": 60,
    "health": 150,
    "speed": 7,
    "growth": 1,
    "aiValue": 3718,
    "cost": 2000,
    "specials": "Immunity to Mind",
    "imageSrc": "./img/Tower/Giants.PNG",
    "damage": "40-60",
    "archerDamage": 0,
    "type": "Fast Tank"
  },
  {
    "name": "Titans",
    "townName": "Tower",
    "level": "7+",
    "attack": 24,
    "defense": 24,
    "damage_low": 40,
    "damage_high": 60,
    "health": 300,
    "speed": 11,
    "growth": 1,
    "aiValue": 7500,
    "cost": 5000,
    "specials": "Ranged (24 shots), No melee penalty, Immunity to Mind, Hates Black Dragons",
    "imageSrc": "./img/Tower/Titans.PNG",
    "damage": "40-60",
    "archerDamage": 24,
    "type": "Archer (24dmg) Fast Tank"
  }
]